!--------------------------------------------------------------------------------
! Copyright (c) 2021 Peter Grünberg Institut, Forschungszentrum Jülich, Germany
! This file is part of FLEUR and available as free software under the conditions
! of the MIT license as expressed in the LICENSE file in more detail.
!--------------------------------------------------------------------------------
MODULE m_dfpt
    USE m_constants
    USE m_types
    USE m_dfpt_check
    USE m_dfpt_test
    USE m_dfpt_init
    USE m_dfpt_sternheimer
    USE m_dfpt_dynmat

    IMPLICIT NONE

CONTAINS
    SUBROUTINE dfpt(juPhon, input)

        TYPE(t_juPhon), INTENT(IN) :: juPhon
        TYPE(t_input),  INTENT(IN) :: input

        WRITE (oUnit,*) '------------------------------------------------------'
        WRITE (oUnit,*) 'This output is generated by juPhon, FLEURs DFPT addon.'
        WRITE (oUnit,*) 'l_dfpt = ', juPhon%l_dfpt
        WRITE (oUnit,*) 'l_jpCheck = ', juPhon%l_jpCheck
        WRITE (oUnit,*) 'l_jpTest = ', juPhon%l_jpTest
        WRITE (oUnit,*) 'l_potout = ', juPhon%l_potout
        WRITE (oUnit,*) 'l_eigout = ', juPhon%l_eigout
        WRITE (oUnit,*) 'l_symTsh = ', juPhon%l_symTsh
        WRITE (oUnit,*) 'l_symTdm = ', juPhon%l_symTdm
        WRITE (oUnit,*) 'l_bfkq = ', juPhon%l_bfkq
        WRITE (oUnit,*) 'jplPlus = ', juPhon%jplPlus
        WRITE (oUnit,*) 'kgqmax = ', juPhon%kgqmax
        WRITE (oUnit,*) 'gqmax = ', juPhon%gqmax
        WRITE (oUnit,*) 'eps_pert = ', juPhon%eps_pert
        WRITE (oUnit,*) 'eDiffCut = ', juPhon%eDiffCut
        WRITE (oUnit,*) 'qpt_ph = ', juPhon%qpt_ph

        IF (juPhon%l_jpCheck) THEN
            CALL dfpt_check()
        END IF

        CALL dfpt_init()

        IF (juPhon%l_jpTest) THEN
            CALL dfpt_test()
        END IF

        CALL dfpt_sternheimer()

        CALL dfpt_dynmat()

        WRITE (oUnit,*) '------------------------------------------------------'
    END SUBROUTINE dfpt
END MODULE m_dfpt
