!--------------------------------------------------------------------------------
! Copyright (c) 2021 Peter Grünberg Institut, Forschungszentrum Jülich, Germany
! This file is part of FLEUR and available as free software under the conditions
! of the MIT license as expressed in the LICENSE file in more detail.
!--------------------------------------------------------------------------------
MODULE m_dfpt
    USE m_constants
    USE m_types
    USE m_dfpt_check
    USE m_dfpt_test
    USE m_dfpt_init
    USE m_dfpt_sternheimer
    USE m_dfpt_dynmat

    IMPLICIT NONE

CONTAINS
    SUBROUTINE dfpt(juPhon, sym, input, atoms, sphhar, stars, rho)

        TYPE(t_juPhon),   INTENT(IN)  :: juPhon
        TYPE(t_sym),      INTENT(IN)  :: sym
        TYPE(t_input),    INTENT(IN)  :: input
        TYPE(t_atoms),    INTENT(IN)  :: atoms
        TYPE(t_sphhar),   INTENT(IN)  :: sphhar
        TYPE(t_stars),    INTENT(IN)  :: stars
        TYPE(t_potden),   INTENT(IN)  :: rho

        TYPE(t_jpPotden)              :: rho0

        INTEGER,          ALLOCATABLE :: recG(:, :)

        WRITE (oUnit,*) '------------------------------------------------------'
        WRITE (oUnit,*) 'This output is generated by juPhon, FLEURs DFPT addon.'
        WRITE (oUnit,*) 'l_dfpt = ', juPhon%l_dfpt
        WRITE (oUnit,*) 'l_jpCheck = ', juPhon%l_jpCheck
        WRITE (oUnit,*) 'l_jpTest = ', juPhon%l_jpTest
        WRITE (oUnit,*) 'l_potout = ', juPhon%l_potout
        WRITE (oUnit,*) 'l_eigout = ', juPhon%l_eigout
        WRITE (oUnit,*) 'l_symTsh = ', juPhon%l_symTsh
        WRITE (oUnit,*) 'l_symTdm = ', juPhon%l_symTdm
        WRITE (oUnit,*) 'l_bfkq = ', juPhon%l_bfkq
        WRITE (oUnit,*) 'jplPlus = ', juPhon%jplPlus
        WRITE (oUnit,*) 'kgqmax = ', juPhon%kgqmax
        WRITE (oUnit,*) 'gqmax = ', juPhon%gqmax
        WRITE (oUnit,*) 'eps_pert = ', juPhon%eps_pert
        WRITE (oUnit,*) 'eDiffCut = ', juPhon%eDiffCut
        WRITE (oUnit,*) 'qpt_ph = ', juPhon%qpt_ph

        IF (juPhon%l_jpCheck) THEN
            ! This function will be used to check the validity of juPhon's
            ! input. I.e. check, whether all prohibited switches are off and,
            ! once there is more expertise considering this topic, check whether
            ! the cutoffs are chosen appropriately.
            CALL dfpt_check()
        END IF

        ! This routine will initialize everything for juPhon that isn't already
        ! provided by the FLEUR code/must be provieded in a modified way.
        ! This includes for example the de-symmetrized MT and pw quantities and
        ! their gradients. Notably, q-dependent quantities are initialized and
        ! constructed elsewhere, within the q-loop.
        CALL dfpt_init(juPhon, sym, input, atoms, sphhar, stars, rho, rho0, recG)

        ! < Imagine starting a q-grid-loop here. >

        IF (juPhon%l_jpTest) THEN
            ! This function will be used to run (parts of) the test suite for
            ! OG juPhon, as provided by CRG.
            CALL dfpt_test()
        END IF

        ! This is where the magic happens. The Sternheimer equation is solved
        ! iteratively, providing the scf part of dfpt calculations.
        CALL dfpt_sternheimer()

        ! Once the first order quantities are converged, we can construct all
        ! additional quantities necessary and from that the dynamical matrix.
        CALL dfpt_dynmat()

        ! < Imagine ending a q-grid-loop here. >

        WRITE (oUnit,*) '------------------------------------------------------'

    END SUBROUTINE dfpt
END MODULE m_dfpt
