set(FLEUR_USE_GITVERSION FALSE)
find_package(Git)
if (Git_FOUND)
    execute_process(COMMAND ${GIT_EXECUTABLE} submodule update  WORKING_DIRECTORY ${PROJECT_SOURCE_DIR} RESULT_VARIABLE _res_update OUTPUT_QUIET ERROR_QUIET)
    if ( _res_update EQUAL 0)
        set(FLEUR_USE_GITVERSION TRUE)
    endif()
else()
    set(FLEUR_WARN_MESSAGE "${FLEUR_WARN_MESSAGE}\nGit excutable not found")
endif()    