#First check if we can compile with ChASE
try_compile(FLEUR_USE_CHASE ${CMAKE_BINARY_DIR} ${CMAKE_SOURCE_DIR}/cmake/tests/test_ChASE.f90 LINK_LIBRARIES ${FLEUR_LIBRARIES})

message("Preinstalled ChASE Library found:${FLEUR_USE_CHASE}")
if (DEFINED CLI_FLEUR_USE_CHASE)
   if (CLI_FLEUR_USE_CHASE)
      if (NOT FLEUR_USE_CHASE)
         if (NOT EXISTS "${PROJECT_SOURCE_DIR}/.git")
                message(FATAL_ERROR "You asked for ChASE to be used, but it cannot be found.\n"
                "Please either provide correct include and link directories for ChASE manually, or use a git-version of FLEUR to download ChASE automatically")
         endif()     
         message(WARNING "You asked for ChASE but cmake couldn't find it. We will try to download and compile ChASE along with FLEUR")
         if(NOT EXISTS "${PROJECT_SOURCE_DIR}/external/chase-git/src" )
         find_package(Git REQUIRED)
         execute_process(COMMAND ${GIT_EXECUTABLE} submodule init external/chase-git WORKING_DIRECTORY ${PROJECT_SOURCE_DIR} RESULT_VARIABLE _res_init OUTPUT_QUIET ERROR_QUIET)
         execute_process(COMMAND ${GIT_EXECUTABLE} submodule update  WORKING_DIRECTORY ${PROJECT_SOURCE_DIR} RESULT_VARIABLE _res_update OUTPUT_QUIET ERROR_QUIET)
         if (_res_init GREATER 0 OR _res_update GREATER 0)
            message(FATAL_ERROR "ChASE source could not be downloaded.\n"
                           "We tried: 'git submodule init external/chase-git && git submodule update' and resulted in error" )
         endif()
	   endif()
	   add_subdirectory (external/chase-git)
	   set(FLEUR_USE_CHASE TRUE)
           set(FLEUR_COMPILE_CHASE true)
           include_directories("${CMAKE_CURRENT_BINARY_DIR}/modules/external")
           include_directories("${CMAKE_CURRENT_BINARY_DIR}/modules/external/static")
       endif()
   else()
       if (FLEUR_USE_CHASE)
           message("CHASE library found, but you explicitely asked not to use it")
	   set(FLEUR_USE_CHASE FALSE)
       endif()
   endif()
endif()

if (FLEUR_USE_CHASE)
   set(FLEUR_DEFINITIONS ${FLEUR_DEFINITIONS} "CPP_CHASE") 
   set(FLEUR_MPI_DEFINITIONS ${FLEUR_MPI_DEFINITIONS} "CPP_CHASE")
endif()

