#Check if we can compile with GPU
if (CLI_FLEUR_USE_GPU)
   #No check is done
   set(FLEUR_USE_GPU TRUE)
   message("GPU:${CLI_FLEUR_USE_GPU}")
   set(FLEUR_MPI_DEFINITIONS ${FLEUR_MPI_DEFINITIONS} "CPP_GPU")
   set(FLEUR_DEFINITIONS ${FLEUR_DEFINITIONS} "CPP_GPU")
   if(${CLI_FLEUR_USE_GPU} MATCHES "acc-gcc")
      set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -fopenacc ")
   elseif(${CLI_FLEUR_USE_GPU} MATCHES "acc")
      set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -acc -cudalib=cublas,cufft,cusolver,cusparse -Minfo=accel -lnvToolsExt")
   elseif(${CLI_Fortran_FLAGS} MATCHES "omp")
      #We try to use OMP offloading
      set(FLEUR_MPI_DEFINITIONS ${FLEUR_MPI_DEFINITIONS} "CPP_OMP_GPU='$omp'")
      set(FLEUR_DEFINITIONS ${FLEUR_DEFINITIONS} "CPP_OMP_GPU='$omp'")
  else()
      message(ERROR,"Choose a GPU mode")
   endif()
   #Check if a CC is given
   STRING(REGEX MATCH ".*:(cc..)" CC_MODE "${CLI_FLEUR_USE_GPU}")
   message("CC:${CC_MODE} ${CMAKE_MATCH_1}")
   if (CC_MODE)
       set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -gpu=${CMAKE_MATCH_1}")
   endif()
   #Now check for cusolverDN library
   try_compile(FLEUR_USE_CUSOLVER ${CMAKE_BINARY_DIR} ${CMAKE_SOURCE_DIR}/cmake/tests/test_cusolverdn.F90 OUTPUT_VARIABLE compile_output)
   if ("$ENV{VERBOSE}")
      message("CusolveDN compile test: ${FLEUR_USE_CUSOLVER}\n${compile_output}")
   endif()

   if (FLEUR_USE_CUSOLVER)
     set(FLEUR_MPI_DEFINITIONS ${FLEUR_MPI_DEFINITIONS} "CPP_CUSOLVER")
     set(FLEUR_DEFINITIONS ${FLEUR_DEFINITIONS} "CPP_CUSOLVER")
   endif()
   #Check also for cuda.h
   try_compile(FLEUR_USE_CUDA_C ${CMAKE_BINARY_DIR} ${CMAKE_SOURCE_DIR}/cmake/tests/test_cuda.c)
   if (FLEUR_USE_CUDA_C)
      set(FLEUR_MPI_DEFINITIONS ${FLEUR_MPI_DEFINITIONS} "CPP_GPU_CUDA")
      set(FLEUR_DEFINITIONS ${FLEUR_DEFINITIONS} "CPP_GPU_CUDA")
   endif()   
else()
   set(FLEUR_USE_GPU FALSE)
   #if we do not use GPU-code we should use OpenMP-on the CPU instead
   if (FLEUR_USE_OPENMP)
      set(FLEUR_MPI_DEFINITIONS ${FLEUR_MPI_DEFINITIONS} "CPP_OMP_CPU='$omp'")
      set(FLEUR_DEFINITIONS ${FLEUR_DEFINITIONS} "CPP_OMP_CPU='$omp'")
   endif()   
endif()
