set(__check_external 0)
if (NOT DEFINED CLI_FLEUR_USE_ELPA)
    set(__check_external 1)
elseif(${CLI_FLEUR_USE_ELPA} MATCHES "external")
    set(__check_external 1)
endif()    
if (__check_external)
   message("Checking for external ELPA")
   #Only External ELPA
    #First check if we can compile with ELPA
    try_compile(FLEUR_USE_ELPA ${CMAKE_BINARY_DIR} ${CMAKE_CURRENT_LIST_DIR}/test_ELPA.f90
    LINK_LIBRARIES ${FLEUR_LIBRARIES} OUTPUT_VARIABLE compile_output)
	if ("$ENV{VERBOSE}")
        message("ELPA compile test: ${FLEUR_USE_ELPA}\nLINK_LIBRARIES ${FLEUR_LIBRARIES}\n${compile_output}")
    endif()
    if (NOT FLEUR_USE_ELPA)
        if (FLEUR_USE_OPENMP AND DEFINED CLI_ELPA_OPENMP)
            set(TEST_LIBRARIES "-lelpa_openmp;${FLEUR_LIBRARIES}")
        else()
            set(TEST_LIBRARIES "-lelpa;${FLEUR_LIBRARIES}")
        endif()
        try_compile(FLEUR_USE_ELPA ${CMAKE_BINARY_DIR} ${CMAKE_CURRENT_LIST_DIR}/test_ELPA.f90
        LINK_LIBRARIES ${TEST_LIBRARIES} OUTPUT_VARIABLE compile_output)
	    if ("$ENV{VERBOSE}")
            message("ELPA compile test: ${FLEUR_USE_ELPA}\nLINK_LIBRARIES ${TEST_LIBRARIES}\n${compile_output}")
        endif()
        if (FLEUR_USE_ELPA)
            set(FLEUR_LIBRARIES "${TEST_LIBRARIES}")
        endif()
    endif()
   
    if (FLEUR_USE_ELPA)
        set(FLEUR_MPI_DEFINITIONS ${FLEUR_MPI_DEFINITIONS} "CPP_ELPA")
        if (DEFINED FLEUR_CPU_PROFILE)
            message(STATUS "External ELPA selected with FLEUR_CPU_PROFILE='${FLEUR_CPU_PROFILE}'.")
            message(STATUS "External ELPA binaries must be compatible with the selected CPU profile.")
        endif()
        if (DEFINED FLEUR_ELPA_KERNEL_MODE)
            message(STATUS "Requested ELPA kernel mode: ${FLEUR_ELPA_KERNEL_MODE} (external ELPA may ignore this).")
            if (NOT FLEUR_ELPA_KERNEL_MODE STREQUAL "generic")
                message(WARNING "External ELPA was found. Non-generic ELPA kernel mode '${FLEUR_ELPA_KERNEL_MODE}' cannot be enforced for external ELPA. Use internal ELPA or provide a matching external ELPA build.")
            endif()
        endif()
    endif()
    message("External ELPA Library found:${FLEUR_USE_ELPA}")
    #if ELPA was found also check for patch and SP
    if (FLEUR_USE_ELPA)
        try_compile(FLEUR_USE_ELPA_PATCH ${CMAKE_BINARY_DIR} ${CMAKE_CURRENT_LIST_DIR}/test_ELPA_transform.f90
            LINK_LIBRARIES ${FLEUR_LIBRARIES} OUTPUT_VARIABLE compile_output)
        if (FLEUR_USE_ELPA_PATCH)
                message("  ELPA Library patch for transform:${FLEUR_USE_ELPA_PATCH}")
                set(FLEUR_MPI_DEFINITIONS ${FLEUR_MPI_DEFINITIONS} "CPP_ELPA_PATCH")
        endif()
        try_compile(FLEUR_USE_ELPA_SP ${CMAKE_BINARY_DIR} ${CMAKE_CURRENT_LIST_DIR}/test_ELPA_sp.f90
            LINK_LIBRARIES ${FLEUR_LIBRARIES} OUTPUT_VARIABLE compile_output)
        if (FLEUR_USE_ELPA_SP)
                message("  ELPA Library Single Precision found:${FLEUR_USE_ELPA_SP}")
                set(FLEUR_MPI_DEFINITIONS ${FLEUR_MPI_DEFINITIONS} "CPP_ELPA_SP")
        endif()
    endif()    

elseif(NOT (${CLI_FLEUR_USE_ELPA} MATCHES "(NO|No|no)"))
    message("Use internal ELPA compilation")
    include(cmake/tests/test_ELPA_internal.cmake)
endif()    