set(__check_external 0)
if (NOT DEFINED CLI_FLEUR_USE_ELPA)
    set(__check_external 1)
elseif(${CLI_FLEUR_USE_ELPA} MATCHES "external")
    set(__check_external 1)
endif()    
if (__check_external)
   message("Checking for external ELPA")
   #Only External ELPA
    #First check if we can compile with ELPA
    try_compile(FLEUR_USE_ELPA ${CMAKE_BINARY_DIR} ${CMAKE_CURRENT_LIST_DIR}/test_ELPA.f90
    LINK_LIBRARIES ${FLEUR_LIBRARIES} OUTPUT_VARIABLE compile_output)
	if ("$ENV{VERBOSE}")
        message("ELPA compile test: ${FLEUR_USE_ELPA}\nLINK_LIBRARIES ${FLEUR_LIBRARIES}\n${compile_output}")
    endif()
    if (NOT FLEUR_USE_ELPA)
        if (FLEUR_USE_OPENMP AND DEFINED CLI_ELPA_OPENMP)
            set(TEST_LIBRARIES "-lelpa_openmp;${FLEUR_LIBRARIES}")
        else()
            set(TEST_LIBRARIES "-lelpa;${FLEUR_LIBRARIES}")
        endif()
        try_compile(FLEUR_USE_ELPA ${CMAKE_BINARY_DIR} ${CMAKE_CURRENT_LIST_DIR}/test_ELPA.f90
        LINK_LIBRARIES ${TEST_LIBRARIES} OUTPUT_VARIABLE compile_output)
	    if ("$ENV{VERBOSE}")
            message("ELPA compile test: ${FLEUR_USE_ELPA}\nLINK_LIBRARIES ${TEST_LIBRARIES}\n${compile_output}")
        endif()
        if (FLEUR_USE_ELPA)
            set(FLEUR_LIBRARIES "${TEST_LIBRARIES}")
        endif()
    endif()

    
    if (FLEUR_USE_ELPA)
        set(FLEUR_MPI_DEFINITIONS ${FLEUR_MPI_DEFINITIONS} "CPP_ELPA" "CPP_ELPA2" "CPP_ELPA_201705003")
    endif()
    message("External ELPA Library found:${FLEUR_USE_ELPA}")
elseif(NOT (${CLI_FLEUR_USE_ELPA} MATCHES "(NO|No|no)"))
    message("Use internal ELPA compilation")
    include(cmake/tests/test_ELPA_internal.cmake)
endif()    