try_compile(FLEUR_USE_PROG_THREAD ${CMAKE_BINARY_DIR} ${CMAKE_SOURCE_DIR}/cmake/tests/test_prog.c
      OUTPUT_VARIABLE outstuff)

message("PROGRESS_THREAD :${FLEUR_USE_PROG_THREAD}")
if ("$ENV{VERBOSE}")
  message("${outstuff}")
endif()
if (FLEUR_USE_PROG_THREAD)
   set(FLEUR_MPI_DEFINITIONS ${FLEUR_MPI_DEFINITIONS} "CPP_PROG_THREAD")
   set(FLEUR_DEFINITIONS ${FLEUR_DEFINITIONS} "CPP_PROG_THREAD")
endif()
