if (CMAKE_Fortran_COMPILER_ID MATCHES "Intel")
   message("Intel Fortran detected")
   set(FLEUR_PRECISION_OPTION "-r8")
elseif (CMAKE_Fortran_COMPILER_ID MATCHES "NVHPC")
  message("NVHPC Fortran detected")
  set(FLEUR_PRECISION_OPTION "-Mr8;-Mr8intrinsics")
elseif (CMAKE_Fortran_COMPILER_ID MATCHES "PGI")
   message("PGI Fortran detected")
   set(FLEUR_PRECISION_OPTION "-Mr8;-Mr8intrinsics")
elseif (CMAKE_Fortran_COMPILER_ID MATCHES "XL")
   message("IBM/BG Fortran detected")
   set(FLEUR_PRECISION_OPTION "-qrealsize=8")
elseif (CMAKE_Fortran_COMPILER_ID MATCHES "GNU")
   message("gfortran detected")
   set(FLEUR_PRECISION_OPTION "-fdefault-real-8;-fdefault-double-8")
elseif (CMAKE_Fortran_COMPILER_ID STREQUAL "LLVMFlang")
   message("LLVM flang detected")
   #-fdefault-real-8 alone promotes DOUBLE PRECISION to kind 16
   set(FLEUR_PRECISION_OPTION "-fdefault-real-8;-fdefault-double-8")
elseif (CMAKE_Fortran_COMPILER_ID MATCHES "Cray")
   message("Cray compiler detected")
   set(FLEUR_PRECISION_OPTION -s real64)
elseif (CMAKE_Fortran_COMPILER_ID MATCHES "NAG")
   message("NAG Fortran detected")
   set(FLEUR_PRECISION_OPTION "-r8")
else()
   message("Unknown compiler ID: ${CMAKE_Fortran_COMPILER_ID}")
endif()

try_run(PRECISION_RUN_OK PRECISION_COMP_OK  ${CMAKE_BINARY_DIR} ${CMAKE_CURRENT_LIST_DIR}/test_precision.f90 COMPILE_DEFINITIONS ${FLEUR_PRECISION_OPTION} )

if (NOT PRECISION_COMP_OK)
   message("Double precision test could not be compiled with: ${FLEUR_PRECISION_OPTION}")
elseif ("${PRECISION_RUN_OK}" STREQUAL "0")
   message("Double precision found")
elseif ("${PRECISION_RUN_OK}" STREQUAL "1")
   message(FATAL_ERROR "Default REAL is not double precision with: ${FLEUR_PRECISION_OPTION}")
elseif ("${PRECISION_RUN_OK}" STREQUAL "2")
   message(WARNING "DOUBLE PRECISION is not 8 bytes with: ${FLEUR_PRECISION_OPTION}")
else()
   message("Double precision message: ${PRECISION_RUN_OK}")
endif()

#Precision option is added manually for FLEUR targets later on
#string(REPLACE ";" " " CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} ${FLEUR_PRECISION_OPTION}")
