#!/bin/sh
if  git rev-parse -q --verify MERGE_HEAD
then
    echo "In merge state"
else  
if git diff-index --cached HEAD -U0 | grep -q -i -w -E '^\+.* STOP'
then 
  git diff-index --cached HEAD -U0 -GSTOP
  cat <<\EOF

It looks like you introduced a stop command in your code.
Please use calls to judft_error instead, as this ensures proper 
termination of the program.

If this is actually a false alarm, please commit again with
the --no-verify option.

EOF
    exit 1
fi
fi
