!--------------------------------------------------------------------------------
! Copyright (c) 2026 Peter Grünberg Institut, Forschungszentrum Jülich, Germany
! This file is part of FLEUR and available as free software under the conditions
! of the MIT license as expressed in the LICENSE file in more detail.
!--------------------------------------------------------------------------------
! Standalone validation of the Nordstrom/Bultmark complex multipole transform.
! The complete frozen l=2 tensor was generated by the independent scratch
! Python implementation of Nordstrom Eqs. (45), (48)-(52), and (59)-(62),
! using an independently validated Python Racah Wigner-3j evaluator.  Values
! are ordered by k, p, r, and t, with the last index varying fastest.  They are
! not generated by the Fortran implementation under test.
!--------------------------------------------------------------------------------
PROGRAM spin_orbital_multipoles_test
   USE m_local_d_spin_multipoles, ONLY: local_d_spin_density_to_multipoles
   USE m_spin_orbital_multipoles
   IMPLICIT NONE

   INTEGER, PARAMETER :: l = 2, dim = 2*(2*l+1)
   REAL, PARAMETER :: tolerance = 2.0e-12
   COMPLEX :: rho(-l:l, 2, -l:l, 2), reconstructed(-l:l, 2, -l:l, 2)
   COMPLEX :: w(0:2*l, 0:1, 0:2*l+1, -(2*l+1):2*l+1)
   COMPLEX :: golden_w(0:2*l, 0:1, 0:2*l+1, -(2*l+1):2*l+1)
   COMPLEX :: adapter_w(0:2*l, 0:1, 0:2*l+1, -(2*l+1):2*l+1)
   COMPLEX :: matrix(dim, dim), a(dim, dim), orbital_matrix(2*l+1,2*l+1), scalar
   COMPLEX :: spinor(2)
   COMPLEX, PARAMETER :: golden_l2(100) = [ &
      CMPLX( 1.35850000000000044e+01,  0.00000000000000000e+00), & ! (0,0,0,0)
      CMPLX(-7.81352993211134939e-01, -1.27279220613578548e-01), & ! (0,1,1,-1)
      CMPLX( 1.45499999999999963e+00,  0.00000000000000000e+00), & ! (0,1,1,0)
      CMPLX( 7.81352993211134939e-01, -1.27279220613578548e-01), & ! (0,1,1,1)
      CMPLX(-4.77183429441199014e-01,  4.71939655491295795e-02), & ! (1,0,1,-1)
      CMPLX(-5.82000000000000117e+00,  0.00000000000000000e+00), & ! (1,0,1,0)
      CMPLX( 4.77183429441199014e-01,  4.71939655491295795e-02), & ! (1,0,1,1)
      CMPLX( 3.00590299905631575e-01,  0.00000000000000000e+00), & ! (1,1,0,0)
      CMPLX(-3.61338781313089163e-02,  2.11115387647999447e-01), & ! (1,1,1,-1)
      CMPLX( 1.33484692283495337e-02,  0.00000000000000000e+00), & ! (1,1,1,0)
      CMPLX( 3.61338781313089163e-02,  2.11115387647999447e-01), & ! (1,1,1,1)
      CMPLX( 6.02168616577541060e-01, -9.80908153700971730e-02), & ! (1,1,2,-2)
      CMPLX( 2.03403566593269192e-01,  6.32877538267962586e-02), & ! (1,1,2,-1)
      CMPLX(-4.80295149952816081e-01,  0.00000000000000000e+00), & ! (1,1,2,0)
      CMPLX(-2.03403566593269192e-01,  6.32877538267962586e-02), & ! (1,1,2,1)
      CMPLX( 6.02168616577541060e-01,  9.80908153700971730e-02), & ! (1,1,2,2)
      CMPLX( 3.10220456627870955e-01,  5.80454076850485997e-03), & ! (2,0,2,-2)
      CMPLX( 2.17060199937087916e-01, -5.00908153700972067e-02), & ! (2,0,2,-1)
      CMPLX( 6.15999999999999326e-01,  0.00000000000000000e+00), & ! (2,0,2,0)
      CMPLX(-2.17060199937087916e-01, -5.00908153700972067e-02), & ! (2,0,2,1)
      CMPLX( 3.10220456627870955e-01, -5.80454076850485997e-03), & ! (2,0,2,2)
      CMPLX(-2.29933203966376121e-01, -1.67562658760921843e-02), & ! (2,1,1,-1)
      CMPLX(-1.99382524992135907e-01,  0.00000000000000000e+00), & ! (2,1,1,0)
      CMPLX( 2.29933203966376121e-01, -1.67562658760921843e-02), & ! (2,1,1,1)
      CMPLX(-3.46981218368622099e-02, -1.50358527959736255e-01), & ! (2,1,2,-2)
      CMPLX( 7.73938769133981127e-03, -1.06201597764496322e-01), & ! (2,1,2,-1)
      CMPLX(-3.68090815370097149e-02,  0.00000000000000000e+00), & ! (2,1,2,0)
      CMPLX(-7.73938769133981127e-03, -1.06201597764496322e-01), & ! (2,1,2,1)
      CMPLX(-3.46981218368622099e-02,  1.50358527959736255e-01), & ! (2,1,2,2)
      CMPLX(-3.44421774110752366e-01,  1.32469913119520142e-02), & ! (2,1,3,-3)
      CMPLX(-2.23932734403945899e-01,  5.16767848624490739e-02), & ! (2,1,3,-2)
      CMPLX( 6.25798916267678446e-02,  4.56047793231506658e-03), & ! (2,1,3,-1)
      CMPLX( 1.32921683328090623e-01,  0.00000000000000000e+00), & ! (2,1,3,0)
      CMPLX(-6.25798916267678446e-02,  4.56047793231506658e-03), & ! (2,1,3,1)
      CMPLX(-2.23932734403945899e-01, -5.16767848624490739e-02), & ! (2,1,3,2)
      CMPLX( 3.44421774110752366e-01,  1.32469913119520142e-02), & ! (2,1,3,3)
      CMPLX(-3.23910418454969595e-01, -4.02492235949962196e-02), & ! (3,0,3,-3)
      CMPLX(-1.39530641795986871e-01,  3.21993788759969701e-02), & ! (3,0,3,-2)
      CMPLX(-9.64106310427207541e-02,  9.53511735587347399e-03), & ! (3,0,3,-1)
      CMPLX( 4.44089209850062616e-16,  0.00000000000000000e+00), & ! (3,0,3,0)
      CMPLX( 9.64106310427207541e-02,  9.53511735587347399e-03), & ! (3,0,3,1)
      CMPLX(-1.39530641795986871e-01, -3.21993788759969701e-02), & ! (3,0,3,2)
      CMPLX( 3.23910418454969595e-01, -4.02492235949962196e-02), & ! (3,0,3,3)
      CMPLX( 2.32248977749816787e-01,  5.13218095905827246e-02), & ! (3,1,2,-2)
      CMPLX( 7.88755111250915991e-02, -1.82020410288672857e-02), & ! (3,1,2,-1)
      CMPLX( 8.58796001258237962e-02,  0.00000000000000000e+00), & ! (3,1,2,0)
      CMPLX(-7.88755111250915991e-02, -1.82020410288672857e-02), & ! (3,1,2,1)
      CMPLX( 2.32248977749816843e-01, -5.13218095905827246e-02), & ! (3,1,2,2)
      CMPLX( 1.90127706944180873e-02,  8.23886730091450831e-02), & ! (3,1,3,-3)
      CMPLX(-7.26730325641605605e-03,  1.65184133831390828e-01), & ! (3,1,3,-2)
      CMPLX( 1.26666943835335791e-02,  5.48890089953121968e-02), & ! (3,1,3,-1)
      CMPLX( 2.83119560854365937e-03,  0.00000000000000000e+00), & ! (3,1,3,0)
      CMPLX(-1.26666943835335773e-02,  5.48890089953121968e-02), & ! (3,1,3,1)
      CMPLX(-7.26730325641605605e-03, -1.65184133831390828e-01), & ! (3,1,3,2)
      CMPLX(-1.90127706944180873e-02,  8.23886730091450831e-02), & ! (3,1,3,3)
      CMPLX( 3.44425044256527757e-01,  2.50998007960222605e-02), & ! (3,1,4,-4)
      CMPLX( 1.24810415308140923e-01, -2.88024035326479126e-02), & ! (3,1,4,-3)
      CMPLX( 4.47958504392531667e-02, -2.45617025120363208e-02), & ! (3,1,4,-2)
      CMPLX(-4.36033255612458884e-02,  1.00623058987490566e-02), & ! (3,1,4,-1)
      CMPLX(-6.44097000943686243e-02,  0.00000000000000000e+00), & ! (3,1,4,0)
      CMPLX( 4.36033255612458884e-02,  1.00623058987490566e-02), & ! (3,1,4,1)
      CMPLX( 4.47958504392531737e-02,  2.45617025120363208e-02), & ! (3,1,4,2)
      CMPLX(-1.24810415308140923e-01, -2.88024035326479126e-02), & ! (3,1,4,3)
      CMPLX( 3.44425044256527757e-01, -2.50998007960222605e-02), & ! (3,1,4,4)
      CMPLX( 4.95488660158513672e-01,  1.08765803449429821e-01), & ! (4,0,4,-4)
      CMPLX( 1.31844063737648676e-01, -3.04255531702266047e-02), & ! (4,0,4,-3)
      CMPLX( 1.36739773993910574e-01,  2.55854046974052793e-03), & ! (4,0,4,-2)
      CMPLX( 6.40108745872809970e-02, -1.47717402893725175e-02), & ! (4,0,4,-1)
      CMPLX(-1.33226762955018785e-15,  0.00000000000000000e+00), & ! (4,0,4,0)
      CMPLX(-6.40108745872809970e-02, -1.47717402893725175e-02), & ! (4,0,4,1)
      CMPLX( 1.36739773993910574e-01, -2.55854046974052793e-03), & ! (4,0,4,2)
      CMPLX(-1.31844063737648676e-01, -3.04255531702266047e-02), & ! (4,0,4,3)
      CMPLX( 4.95488660158513672e-01, -1.08765803449429821e-01), & ! (4,0,4,4)
      CMPLX(-3.97913719113686393e-01, -1.13828551888547985e-01), & ! (4,1,3,-3)
      CMPLX(-5.44546587997034801e-02,  1.25664597230084971e-02), & ! (4,1,3,-2)
      CMPLX(-8.01246461580989167e-02, -5.83904303986145738e-03), & ! (4,1,3,-1)
      CMPLX(-5.36747500786405388e-02,  0.00000000000000000e+00), & ! (4,1,3,0)
      CMPLX( 8.01246461580989167e-02, -5.83904303986145738e-03), & ! (4,1,3,1)
      CMPLX(-5.44546587997034731e-02, -1.25664597230084989e-02), & ! (4,1,3,2)
      CMPLX( 3.97913719113686393e-01, -1.13828551888547985e-01), & ! (4,1,3,3)
      CMPLX(-1.85924450340905802e-02, -8.05672618143924157e-02), & ! (4,1,4,-4)
      CMPLX( 3.52036934318473438e-02, -2.12703182749629377e-01), & ! (4,1,4,-3)
      CMPLX(-2.26502986367936032e-02, -9.81512940927723593e-02), & ! (4,1,4,-2)
      CMPLX( 4.02035848020834349e-03, -5.51682524784143091e-02), & ! (4,1,4,-1)
      CMPLX(-1.10102051443364459e-02,  0.00000000000000000e+00), & ! (4,1,4,0)
      CMPLX(-4.02035848020834349e-03, -5.51682524784143161e-02), & ! (4,1,4,1)
      CMPLX(-2.26502986367936032e-02,  9.81512940927723593e-02), & ! (4,1,4,2)
      CMPLX(-3.52036934318473438e-02, -2.12703182749629377e-01), & ! (4,1,4,3)
      CMPLX(-1.85924450340905802e-02,  8.05672618143924157e-02), & ! (4,1,4,4)
      CMPLX(-5.15921505657595203e-01, -8.92941067484299411e-02), & ! (4,1,5,-5)
      CMPLX(-1.08765803449429876e-01,  2.50998007960222778e-02), & ! (4,1,5,-4)
      CMPLX(-5.98477727920937105e-02,  2.18249006993092610e-02), & ! (4,1,5,-3)
      CMPLX(-2.38060860350001284e-02,  5.49371216192308821e-03), & ! (4,1,5,-2)
      CMPLX( 4.05402205719443895e-02,  2.95434805787447548e-03), & ! (4,1,5,-1)
      CMPLX( 4.29398000629116275e-02,  0.00000000000000000e+00), & ! (4,1,5,0)
      CMPLX(-4.05402205719443895e-02,  2.95434805787447548e-03), & ! (4,1,5,1)
      CMPLX(-2.38060860350001284e-02, -5.49371216192308821e-03), & ! (4,1,5,2)
      CMPLX( 5.98477727920937105e-02,  2.18249006993092610e-02), & ! (4,1,5,3)
      CMPLX(-1.08765803449429876e-01, -2.50998007960222778e-02), & ! (4,1,5,4)
      CMPLX( 5.15921505657595203e-01, -8.92941067484299411e-02) ] ! (4,1,5,5)
   REAL :: max_roundtrip, max_roundtrip_relative, max_hermiticity, max_scalar_error, max_unpolarized
   REAL :: max_complete_golden, max_golden, max_frozen_inverse, scale, nl4, ns1, bracket415, prefactor415
   REAL :: max_adapter_golden, max_adapter_direct
   INTEGER :: failures, component_count, invalid_nonzero, golden_index, adapter_invalid_nonzero
   INTEGER :: golden_k, golden_p, golden_r, golden_t, adapter_k, adapter_p, adapter_r, adapter_t
   INTEGER :: i, j, m, mp, k, p, r, t
   CHARACTER(LEN=256) :: test_mode

   CALL GET_COMMAND_ARGUMENT(1, test_mode)
   IF (INDEX(TRIM(test_mode), "--api-failure-") == 1 .OR. &
       INDEX(TRIM(test_mode), "--adapter-api-failure-") == 1) THEN
      CALL run_api_failure_case(TRIM(test_mode))
      WRITE(*,'(A)') "FAIL API misuse was not rejected: "//TRIM(test_mode)
      ERROR STOP "spin_orbital_multipoles_test: API misuse was not rejected"
   END IF

   failures = 0
   max_roundtrip = 0.0
   max_roundtrip_relative = 0.0
   max_hermiticity = 0.0
   max_scalar_error = 0.0
   max_unpolarized = 0.0
   max_complete_golden = 0.0
   max_golden = 0.0
   max_frozen_inverse = 0.0
   max_adapter_golden = 0.0
   max_adapter_direct = 0.0

   CALL test_general_l(0, failures)
   CALL test_general_l(1, failures)
   CALL test_general_l(3, failures)

   component_count = 0
   DO k = 0, 2*l
      DO p = 0, 1
         DO r = ABS(k-p), k+p
            component_count = component_count + 2*r + 1
         END DO
      END DO
   END DO
   CALL check_integer("l=2 coupled component count", component_count, 100, failures)

   rho = CMPLX(0.0, 0.0)
   rho(0, 1, 0, 1) = 1.0
   CALL spin_orbital_density_to_multipoles(l, rho, w)
   invalid_nonzero = 0
   DO k = 0, 2*l
      DO p = 0, 1
         DO r = 0, 2*l+1
            DO t = -(2*l+1), 2*l+1
               IF (.NOT. valid_component(k, p, r, t) .AND. ABS(w(k, p, r, t)) > 0.0) &
                  invalid_nonzero = invalid_nonzero + 1
            END DO
         END DO
      END DO
   END DO
   CALL check_integer("invalid dense entries remain exactly zero", invalid_nonzero, 0, failures)

   DO i = 1, dim
      DO j = 1, dim
         rho = CMPLX(0.0, 0.0)
         CALL set_flat_density_element(rho, i, j, CMPLX(1.0, 0.0))
         CALL check_roundtrip(rho, w, reconstructed, max_roundtrip, max_roundtrip_relative, failures)
      END DO
   END DO
   CALL initialize_general_matrix(matrix)
   CALL matrix_to_density(matrix, rho)
   CALL check_roundtrip(rho, w, reconstructed, max_roundtrip, max_roundtrip_relative, failures)
   CALL initialize_hermitian_matrix(matrix)
   CALL matrix_to_density(matrix, rho)
   CALL check_roundtrip(rho, w, reconstructed, max_roundtrip, max_roundtrip_relative, failures)
   CALL initialize_general_matrix(a)
   matrix = MATMUL(a, CONJG(TRANSPOSE(a)))
   CALL matrix_to_density(matrix, rho)
   CALL check_roundtrip(rho, w, reconstructed, max_roundtrip, max_roundtrip_relative, failures)
   CALL check_bound("all analytic density-multipole-density round trips", max_roundtrip, tolerance, failures)

   CALL initialize_hermitian_matrix(matrix)
   CALL matrix_to_density(matrix, rho)
   CALL spin_orbital_density_to_multipoles(l, rho, w)
   CALL check_complex("w(0,0,0,0) equals trace", w(0,0,0,0), trace_density(rho), tolerance, failures)

   CALL test_spin_state("+z", [CMPLX(1.0,0.0), CMPLX(0.0,0.0)], failures)
   CALL test_spin_state("-z", [CMPLX(0.0,0.0), CMPLX(1.0,0.0)], failures)
   spinor = [CMPLX(1.0,0.0), CMPLX(1.0,0.0)]/SQRT(2.0)
   CALL test_spin_state("+x", spinor, failures)
   spinor = [CMPLX(1.0,0.0), CMPLX(-1.0,0.0)]/SQRT(2.0)
   CALL test_spin_state("-x", spinor, failures)
   spinor = [CMPLX(1.0,0.0), CMPLX(0.0,1.0)]/SQRT(2.0)
   CALL test_spin_state("+y", spinor, failures)
   spinor = [CMPLX(1.0,0.0), CMPLX(0.0,-1.0)]/SQRT(2.0)
   CALL test_spin_state("-y", spinor, failures)

   CALL initialize_orbital_hermitian(orbital_matrix)
   rho = CMPLX(0.0, 0.0)
   DO m = -l, l
      DO mp = -l, l
         rho(m,1,mp,1) = 0.5*orbital_matrix(m+l+1,mp+l+1)
         rho(m,2,mp,2) = 0.5*orbital_matrix(m+l+1,mp+l+1)
      END DO
   END DO
   CALL spin_orbital_density_to_multipoles(l, rho, w)
   DO k = 0, 2*l
      DO r = ABS(k-1), k+1
         DO t = -r, r
            max_unpolarized = MAX(max_unpolarized, ABS(w(k,1,r,t)))
         END DO
      END DO
   END DO
   CALL check_bound("all p=1 tensors vanish for spin-unpolarized density", &
                    max_unpolarized, tolerance, failures)

   CALL initialize_hermitian_matrix(matrix)
   CALL matrix_to_density(matrix, rho)
   CALL spin_orbital_density_to_multipoles(l, rho, w)
   DO k = 0, 2*l
      DO p = 0, 1
         DO r = ABS(k-p), k+p
            scalar = CMPLX(0.0, 0.0)
            scale = 0.0
            DO t = -r, r
               max_hermiticity = MAX(max_hermiticity, &
                  ABS(CONJG(w(k,p,r,t))-parity_test(t)*w(k,p,r,-t)))
               scalar = scalar + parity_test(t)*w(k,p,r,-t)*w(k,p,r,t)
               scale = scale + ABS(w(k,p,r,t))**2
            END DO
            max_scalar_error = MAX(max_scalar_error, ABS(scalar-CMPLX(scale,0.0)))
            IF (REAL(scalar) < -tolerance) failures = failures + 1
         END DO
      END DO
   END DO
   CALL check_bound("Hermitian-density coupled-tensor conjugation", max_hermiticity, tolerance, failures)
   CALL check_bound("coupled-tensor scalar product is sum of magnitudes", &
                    max_scalar_error, tolerance, failures)

   CALL initialize_golden_density(matrix)
   CALL matrix_to_density(matrix, rho)
   CALL spin_orbital_density_to_multipoles(l, rho, w)
   invalid_nonzero = 0
   DO k = 0, 2*l
      DO p = 0, 1
         DO r = 0, 2*l+1
            DO t = -(2*l+1), 2*l+1
               IF (.NOT. valid_component(k,p,r,t) .AND. ABS(w(k,p,r,t)) > 0.0) &
                  invalid_nonzero = invalid_nonzero+1
            END DO
         END DO
      END DO
   END DO
   CALL check_integer("complete frozen-fixture invalid dense entries", invalid_nonzero, 0, failures)
   golden_w = CMPLX(0.0, 0.0)
   golden_index = 0
   golden_k = -1
   golden_p = -1
   golden_r = -1
   golden_t = 0
   DO k = 0, 2*l
      DO p = 0, 1
         DO r = ABS(k-p), k+p
            DO t = -r, r
               golden_index = golden_index+1
               golden_w(k,p,r,t) = golden_l2(golden_index)
               IF (ABS(w(k,p,r,t)-golden_l2(golden_index)) > max_complete_golden) THEN
                  max_complete_golden = ABS(w(k,p,r,t)-golden_l2(golden_index))
                  golden_k = k
                  golden_p = p
                  golden_r = r
                  golden_t = t
               END IF
            END DO
         END DO
      END DO
   END DO
   CALL check_integer("complete frozen l=2 component count", golden_index, 100, failures)
   CALL check_bound("complete frozen independent l=2 forward fixture", max_complete_golden, tolerance, failures)
   WRITE(*,'(A,4(I0,1X))') "Maximum golden-error location (k,p,r,t): ", &
                           golden_k, golden_p, golden_r, golden_t

   CALL local_d_spin_density_to_multipoles(rho,adapter_w)
   adapter_invalid_nonzero = 0
   adapter_k = -1
   adapter_p = -1
   adapter_r = -1
   adapter_t = 0
   DO k = 0, 2*l
      DO p = 0, 1
         DO r = 0, 2*l+1
            DO t = -(2*l+1), 2*l+1
               IF (valid_component(k,p,r,t)) THEN
                  IF (ABS(adapter_w(k,p,r,t)-golden_w(k,p,r,t)) > max_adapter_golden) THEN
                     max_adapter_golden = ABS(adapter_w(k,p,r,t)-golden_w(k,p,r,t))
                     adapter_k = k
                     adapter_p = p
                     adapter_r = r
                     adapter_t = t
                  END IF
               ELSE IF (ABS(adapter_w(k,p,r,t)) > 0.0) THEN
                  adapter_invalid_nonzero = adapter_invalid_nonzero+1
               END IF
            END DO
         END DO
      END DO
   END DO
   max_adapter_direct = MAXVAL(ABS(adapter_w-w))
   CALL check_bound("d-spin adapter complete frozen l=2 fixture", max_adapter_golden, tolerance, failures)
   WRITE(*,'(A,4(I0,1X))') "Maximum adapter-error location (k,p,r,t): ", &
                           adapter_k, adapter_p, adapter_r, adapter_t
   CALL check_bound("d-spin adapter agrees with direct core", max_adapter_direct, tolerance, failures)
   CALL check_integer("d-spin adapter invalid dense entries", adapter_invalid_nonzero, 0, failures)
   CALL test_adapter_convention_controls(rho,golden_w,failures)

   CALL spin_orbital_multipoles_to_density(l, golden_w, reconstructed)
   max_frozen_inverse = MAXVAL(ABS(reconstructed-rho))
   CALL check_bound("frozen independent l=2 tensor analytic inverse", max_frozen_inverse, tolerance, failures)

   max_golden = 0.0
   DO t = -5, 5
      max_golden = MAX(max_golden, ABS(w(4,1,5,t)-golden_w(4,1,5,t)))
      WRITE(*,'(A,I3,2(A,2ES20.11),A,ES14.6)') "w415 t=", t, " expected=", golden_w(4,1,5,t), &
         " actual=", w(4,1,5,t), " error=", ABS(w(4,1,5,t)-golden_w(4,1,5,t))
   END DO
   CALL check_bound("frozen independent w(4,1,5,t) fixture", max_golden, tolerance, failures)

   nl4 = 24.0/SQRT(362880.0)
   ns1 = 1.0/SQRT(6.0)
   bracket415 = -5.0/SQRT(495.0)
   prefactor415 = parity_test(4+1+l)/(nl4*ns1*bracket415)
   CALL check_real("n_l4", nl4, 1.0/SQRT(630.0), tolerance, failures)
   CALL check_real("n_s1", ns1, 1.0/SQRT(6.0), tolerance, failures)
   CALL check_real("[4 1 5]", bracket415, -5.0/SQRT(495.0), tolerance, failures)
   CALL check_real("validated w415 source-form prefactor", prefactor415, &
                   2.7357631476427190e+02, tolerance, failures)

   WRITE(*,'(A,ES14.6)') "Maximum analytic round-trip error: ", max_roundtrip
   WRITE(*,'(A,ES14.6)') "Maximum relative round-trip error: ", max_roundtrip_relative
   WRITE(*,'(A,ES14.6)') "Maximum Hermiticity-relation error: ", max_hermiticity
   WRITE(*,'(A,ES14.6)') "Maximum tensor scalar-product error: ", max_scalar_error
   WRITE(*,'(A,ES14.6)') "Maximum spin-unpolarized p=1 magnitude: ", max_unpolarized
   WRITE(*,'(A,ES14.6)') "Maximum complete frozen l=2 forward error: ", max_complete_golden
   WRITE(*,'(A,ES14.6)') "Maximum d-spin adapter golden error: ", max_adapter_golden
   WRITE(*,'(A,ES14.6)') "Maximum d-spin adapter direct-core error: ", max_adapter_direct
   WRITE(*,'(A,ES14.6)') "Maximum frozen-tensor inverse error: ", max_frozen_inverse
   WRITE(*,'(A,ES14.6)') "Maximum frozen w415 error: ", max_golden
   CALL expect_api_failure("--api-failure-negative-l", failures)
   CALL expect_api_failure("--api-failure-large-l", failures)
   CALL expect_api_failure("--api-failure-rho-shape", failures)
   CALL expect_api_failure("--api-failure-w-shape", failures)
   CALL expect_api_failure("--adapter-api-failure-rho-shape", failures)
   CALL expect_api_failure("--adapter-api-failure-w-shape", failures)
   IF (failures > 0) THEN
      WRITE(*,'(A,I0)') "SPIN-ORBITAL MULTIPOLES TEST: FAIL, failures = ", failures
      ERROR STOP 1
   END IF
   WRITE(*,'(A)') "SPIN-ORBITAL MULTIPOLES TEST: PASS"

CONTAINS

   SUBROUTINE test_general_l(ll, failures)
      INTEGER, INTENT(IN) :: ll
      INTEGER, INTENT(INOUT) :: failures

      COMPLEX, ALLOCATABLE :: local_rho(:,:,:,:), local_w(:,:,:,:), local_reconstructed(:,:,:,:)
      COMPLEX :: upper_value
      REAL :: roundtrip_error, hermiticity_error
      INTEGER :: local_dim, local_count, local_invalid
      INTEGER :: mm, mmp, ss, ssp, row, col, kk, pp, rr, tt
      CHARACTER(LEN=80) :: label

      local_dim = 2*(2*ll+1)
      ALLOCATE(local_rho(-ll:ll,2,-ll:ll,2))
      ALLOCATE(local_reconstructed(-ll:ll,2,-ll:ll,2))
      ALLOCATE(local_w(0:2*ll,0:1,0:2*ll+1,-(2*ll+1):2*ll+1))

      DO mm = -ll, ll
         DO ss = 1, 2
            row = 2*(mm+ll)+ss
            DO mmp = -ll, ll
               DO ssp = 1, 2
                  col = 2*(mmp+ll)+ssp
                  IF (row == col) THEN
                     local_rho(mm,ss,mmp,ssp) = 0.19*row+0.005*row*row
                  ELSE IF (row < col) THEN
                     local_rho(mm,ss,mmp,ssp) = CMPLX(0.014*(row+2*col)/(1+col-row), &
                                                              0.006*(2*row-col)/(1+col-row))
                  ELSE
                     upper_value = CMPLX(0.014*(col+2*row)/(1+row-col), &
                                         0.006*(2*col-row)/(1+row-col))
                     local_rho(mm,ss,mmp,ssp) = CONJG(upper_value)
                  END IF
               END DO
            END DO
         END DO
      END DO

      CALL spin_orbital_density_to_multipoles(ll, local_rho, local_w)
      local_count = 0
      local_invalid = 0
      hermiticity_error = 0.0
      DO kk = 0, 2*ll
         DO pp = 0, 1
            DO rr = 0, 2*ll+1
               DO tt = -(2*ll+1), 2*ll+1
                  IF (valid_component(kk,pp,rr,tt)) THEN
                     local_count = local_count+1
                     hermiticity_error = MAX(hermiticity_error, &
                        ABS(CONJG(local_w(kk,pp,rr,tt))-parity_test(tt)*local_w(kk,pp,rr,-tt)))
                  ELSE IF (ABS(local_w(kk,pp,rr,tt)) > 0.0) THEN
                     local_invalid = local_invalid+1
                  END IF
               END DO
            END DO
         END DO
      END DO
      WRITE(label,'("l=",I0," coupled component count")') ll
      CALL check_integer(TRIM(label), local_count, 4*(2*ll+1)**2, failures)
      WRITE(label,'("l=",I0," invalid dense entries")') ll
      CALL check_integer(TRIM(label), local_invalid, 0, failures)
      IF (ll == 0) CALL check_integer("l=0 has only charge plus three spin components", local_count, 4, failures)

      CALL spin_orbital_multipoles_to_density(ll, local_w, local_reconstructed)
      roundtrip_error = MAXVAL(ABS(local_reconstructed-local_rho))
      WRITE(label,'("l=",I0," deterministic Hermitian round trip")') ll
      CALL check_bound(TRIM(label), roundtrip_error, tolerance, failures)
      WRITE(label,'("l=",I0," Hermiticity relation")') ll
      CALL check_bound(TRIM(label), hermiticity_error, tolerance, failures)
      WRITE(*,'(A,I0,2(A,ES14.6))') "General-l summary l=", ll, &
         ": round trip = ", roundtrip_error, ", Hermiticity = ", hermiticity_error
   END SUBROUTINE test_general_l

   SUBROUTINE expect_api_failure(argument, failures)
      CHARACTER(LEN=*), INTENT(IN) :: argument
      INTEGER, INTENT(INOUT) :: failures

      CHARACTER(LEN=1024) :: executable, command
      INTEGER :: command_status, exit_status

      CALL GET_COMMAND_ARGUMENT(0, executable)
      command = '"'//TRIM(executable)//'" '//TRIM(argument)
      CALL EXECUTE_COMMAND_LINE(TRIM(command), WAIT=.TRUE., EXITSTAT=exit_status, CMDSTAT=command_status)
      IF (command_status /= 0 .OR. exit_status == 0) THEN
         failures = failures+1
         WRITE(*,'(A,2I8)') "FAIL expected API rejection "//TRIM(argument)//": ", &
                            command_status, exit_status
      ELSE
         WRITE(*,'(A,I0)') "PASS expected API rejection "//TRIM(argument)//": exit status ", exit_status
      END IF
   END SUBROUTINE expect_api_failure

   SUBROUTINE run_api_failure_case(argument)
      CHARACTER(LEN=*), INTENT(IN) :: argument

      COMPLEX, ALLOCATABLE :: bad_rho(:,:,:,:), bad_w(:,:,:,:)

      SELECT CASE (argument)
      CASE ("--api-failure-negative-l")
         ALLOCATE(bad_rho(1,2,1,2), bad_w(1,2,2,3))
         CALL spin_orbital_density_to_multipoles(-1, bad_rho, bad_w)
      CASE ("--api-failure-large-l")
         ALLOCATE(bad_rho(1,2,1,2), bad_w(1,2,2,3))
         CALL spin_orbital_multipoles_to_density(4, bad_w, bad_rho)
      CASE ("--api-failure-rho-shape")
         ALLOCATE(bad_rho(4,2,5,2), bad_w(5,2,6,11))
         CALL spin_orbital_density_to_multipoles(2, bad_rho, bad_w)
      CASE ("--api-failure-w-shape")
         ALLOCATE(bad_rho(5,2,5,2), bad_w(5,2,5,11))
         CALL spin_orbital_multipoles_to_density(2, bad_w, bad_rho)
      CASE ("--adapter-api-failure-rho-shape")
         ALLOCATE(bad_rho(4,2,5,2), bad_w(5,2,6,11))
         CALL local_d_spin_density_to_multipoles(bad_rho,bad_w)
      CASE ("--adapter-api-failure-w-shape")
         ALLOCATE(bad_rho(5,2,5,2), bad_w(5,2,5,11))
         CALL local_d_spin_density_to_multipoles(bad_rho,bad_w)
      CASE DEFAULT
         ERROR STOP "Unknown API-failure test"
      END SELECT
   END SUBROUTINE run_api_failure_case

   SUBROUTINE test_adapter_convention_controls(reference_rho,reference_w,failures)
      COMPLEX, INTENT(IN) :: reference_rho(-l:l,2,-l:l,2)
      COMPLEX, INTENT(IN) :: reference_w(0:2*l,0:1,0:2*l+1,-(2*l+1):2*l+1)
      INTEGER, INTENT(INOUT) :: failures

      COMPLEX :: wrong_rho(-l:l,2,-l:l,2), wrong_w(0:2*l,0:1,0:2*l+1,-(2*l+1):2*l+1)
      COMPLEX :: general_rho(-l:l,2,-l:l,2), general_w(0:2*l,0:1,0:2*l+1,-(2*l+1):2*l+1)
      COMPLEX :: general_matrix(dim,dim)
      REAL :: orbital_partial_transpose_difference, spin_swap_difference, conjugation_difference
      REAL :: full_adjoint_difference
      INTEGER :: mm, mmp, ss, ssp

      DO mm = -l, l
         DO ss = 1, 2
            DO mmp = -l, l
               DO ssp = 1, 2
                  wrong_rho(mm,ss,mmp,ssp) = reference_rho(mmp,ss,mm,ssp)
               END DO
            END DO
         END DO
      END DO
      CALL local_d_spin_density_to_multipoles(wrong_rho,wrong_w)
      orbital_partial_transpose_difference = MAXVAL(ABS(wrong_w-reference_w))
      CALL check_separation("orbital partial transpose changes frozen tensor", &
                            orbital_partial_transpose_difference,failures)

      DO mm = -l, l
         DO ss = 1, 2
            DO mmp = -l, l
               DO ssp = 1, 2
                  wrong_rho(mm,ss,mmp,ssp) = reference_rho(mm,3-ss,mmp,3-ssp)
               END DO
            END DO
         END DO
      END DO
      CALL local_d_spin_density_to_multipoles(wrong_rho,wrong_w)
      spin_swap_difference = MAXVAL(ABS(wrong_w-reference_w))
      CALL check_separation("swapped spin indices change frozen tensor",spin_swap_difference,failures)

      wrong_rho = CONJG(reference_rho)
      CALL local_d_spin_density_to_multipoles(wrong_rho,wrong_w)
      conjugation_difference = MAXVAL(ABS(wrong_w-reference_w))
      CALL check_separation("complex conjugation changes frozen tensor",conjugation_difference,failures)

      CALL initialize_general_matrix(general_matrix)
      CALL matrix_to_density(general_matrix,general_rho)
      CALL local_d_spin_density_to_multipoles(general_rho,general_w)
      DO mm = -l, l
         DO ss = 1, 2
            DO mmp = -l, l
               DO ssp = 1, 2
                  wrong_rho(mm,ss,mmp,ssp) = CONJG(general_rho(mmp,ssp,mm,ss))
               END DO
            END DO
         END DO
      END DO
      CALL local_d_spin_density_to_multipoles(wrong_rho,wrong_w)
      full_adjoint_difference = MAXVAL(ABS(wrong_w-general_w))
      CALL check_separation("full adjoint is detectable for general density",full_adjoint_difference,failures)

      WRITE(*,'(A,ES14.6)') "Orbital-partial-transpose tensor separation: ", &
                            orbital_partial_transpose_difference
      WRITE(*,'(A,ES14.6)') "Spin-swap tensor separation: ",spin_swap_difference
      WRITE(*,'(A,ES14.6)') "Complex-conjugation tensor separation: ",conjugation_difference
      WRITE(*,'(A,ES14.6)') "General-density full-adjoint tensor separation: ",full_adjoint_difference
   END SUBROUTINE test_adapter_convention_controls

   SUBROUTINE check_roundtrip(input, multipoles, output, maximum, maximum_relative, failures)
      COMPLEX, INTENT(IN) :: input(-l:l,2,-l:l,2)
      COMPLEX, INTENT(OUT) :: multipoles(0:2*l,0:1,0:2*l+1,-(2*l+1):2*l+1)
      COMPLEX, INTENT(OUT) :: output(-l:l,2,-l:l,2)
      REAL, INTENT(INOUT) :: maximum, maximum_relative
      INTEGER, INTENT(INOUT) :: failures

      REAL :: local_error

      CALL spin_orbital_density_to_multipoles(l, input, multipoles)
      CALL spin_orbital_multipoles_to_density(l, multipoles, output)
      local_error = MAXVAL(ABS(output-input))
      maximum = MAX(maximum, local_error)
      maximum_relative = MAX(maximum_relative, local_error/MAX(MAXVAL(ABS(input)), TINY(1.0)))
      IF (local_error > tolerance) failures = failures + 1
   END SUBROUTINE check_roundtrip

   SUBROUTINE test_spin_state(label, state, failures)
      CHARACTER(LEN=*), INTENT(IN) :: label
      COMPLEX, INTENT(IN) :: state(2)
      INTEGER, INTENT(INOUT) :: failures

      COMPLEX :: local_rho(-l:l,2,-l:l,2)
      COMPLEX :: local_w(0:2*l,0:1,0:2*l+1,-(2*l+1):2*l+1)
      COMPLEX :: spherical(-1:1)
      INTEGER :: sa, sb, y

      local_rho = CMPLX(0.0,0.0)
      DO sa = 1, 2
         DO sb = 1, 2
            local_rho(0,sa,0,sb) = state(sa)*CONJG(state(sb))
         END DO
      END DO
      spherical(0) = ABS(state(1))**2-ABS(state(2))**2
      spherical(1) = -SQRT(2.0)*CONJG(state(1))*state(2)
      spherical(-1) = SQRT(2.0)*CONJG(state(2))*state(1)
      CALL spin_orbital_density_to_multipoles(l, local_rho, local_w)
      CALL check_complex(label//" trace", local_w(0,0,0,0), CMPLX(1.0,0.0), tolerance, failures)
      DO y = -1, 1
         CALL check_complex(label//" w011=-w01", local_w(0,1,1,y), -spherical(y), &
                            tolerance, failures)
      END DO
   END SUBROUTINE test_spin_state

   SUBROUTINE initialize_general_matrix(output)
      COMPLEX, INTENT(OUT) :: output(dim,dim)
      INTEGER :: row, col

      DO row = 1, dim
         DO col = 1, dim
            output(row,col) = CMPLX(0.031*row-0.017*col+0.002*row*col, &
                                    0.019*row+0.023*col-0.001*row*col)
         END DO
      END DO
   END SUBROUTINE initialize_general_matrix

   SUBROUTINE initialize_hermitian_matrix(output)
      COMPLEX, INTENT(OUT) :: output(dim,dim)
      INTEGER :: row, col

      output = CMPLX(0.0,0.0)
      DO row = 1, dim
         output(row,row) = 0.21*row+0.007*row*row
         DO col = row+1, dim
            output(row,col) = CMPLX(0.012*(row+col)/(1+col-row), &
                                             0.008*(2*row-col)/(1+col-row))
            output(col,row) = CONJG(output(row,col))
         END DO
      END DO
   END SUBROUTINE initialize_hermitian_matrix

   SUBROUTINE initialize_golden_density(output)
      COMPLEX, INTENT(OUT) :: output(dim,dim)
      INTEGER :: row, col

      output = CMPLX(0.0,0.0)
      DO row = 1, dim
         output(row,row) = 0.17*row+0.011*row*row
         DO col = row+1, dim
            output(row,col) = CMPLX(0.013*(row+2*col)/(1+col-row), &
                                    0.009*(2*row-col)/(1+col-row))
            output(col,row) = CONJG(output(row,col))
         END DO
      END DO
   END SUBROUTINE initialize_golden_density

   SUBROUTINE initialize_orbital_hermitian(output)
      COMPLEX, INTENT(OUT) :: output(5,5)
      INTEGER :: row, col

      output = CMPLX(0.0,0.0)
      DO row = 1, 5
         output(row,row) = 0.3+0.1*row
         DO col = row+1, 5
            output(row,col) = CMPLX(0.02*(row+col),0.015*(row-col))
            output(col,row) = CONJG(output(row,col))
         END DO
      END DO
   END SUBROUTINE initialize_orbital_hermitian

   SUBROUTINE matrix_to_density(input, output)
      COMPLEX, INTENT(IN) :: input(dim,dim)
      COMPLEX, INTENT(OUT) :: output(-l:l,2,-l:l,2)
      INTEGER :: row, col, mm, mmp, ss, ssp

      DO mm = -l, l
         DO ss = 1, 2
            row = 2*(mm+l)+ss
            DO mmp = -l, l
               DO ssp = 1, 2
                  col = 2*(mmp+l)+ssp
                  output(mm,ss,mmp,ssp) = input(row,col)
               END DO
            END DO
         END DO
      END DO
   END SUBROUTINE matrix_to_density

   SUBROUTINE set_flat_density_element(output, row, col, value)
      COMPLEX, INTENT(INOUT) :: output(-l:l,2,-l:l,2)
      INTEGER, INTENT(IN) :: row, col
      COMPLEX, INTENT(IN) :: value
      INTEGER :: mm, mmp, ss, ssp

      mm = (row-1)/2-l
      ss = MOD(row-1,2)+1
      mmp = (col-1)/2-l
      ssp = MOD(col-1,2)+1
      output(mm,ss,mmp,ssp) = value
   END SUBROUTINE set_flat_density_element

   COMPLEX FUNCTION trace_density(input)
      COMPLEX, INTENT(IN) :: input(-l:l,2,-l:l,2)
      INTEGER :: mm, ss

      trace_density = CMPLX(0.0,0.0)
      DO mm = -l, l
         DO ss = 1, 2
            trace_density = trace_density+input(mm,ss,mm,ss)
         END DO
      END DO
   END FUNCTION trace_density

   LOGICAL FUNCTION valid_component(kk, pp, rr, tt)
      INTEGER, INTENT(IN) :: kk, pp, rr, tt

      valid_component = rr >= ABS(kk-pp) .AND. rr <= kk+pp .AND. ABS(tt) <= rr
   END FUNCTION valid_component

   REAL FUNCTION parity_test(n)
      INTEGER, INTENT(IN) :: n

      parity_test = MERGE(1.0,-1.0,MOD(ABS(n),2)==0)
   END FUNCTION parity_test

   SUBROUTINE check_bound(label, value, bound, failures)
      CHARACTER(LEN=*), INTENT(IN) :: label
      REAL, INTENT(IN) :: value, bound
      INTEGER, INTENT(INOUT) :: failures

      IF (value > bound) THEN
         failures = failures+1
         WRITE(*,'(A,2ES18.8)') "FAIL "//TRIM(label)//": ", value, bound
      ELSE
         WRITE(*,'(A,ES14.6)') "PASS "//TRIM(label)//": ", value
      END IF
   END SUBROUTINE check_bound

   SUBROUTINE check_separation(label,value,failures)
      CHARACTER(LEN=*), INTENT(IN) :: label
      REAL, INTENT(IN) :: value
      INTEGER, INTENT(INOUT) :: failures

      IF (value <= 1000.0*tolerance) THEN
         failures = failures+1
         WRITE(*,'(A,ES18.8)') "FAIL "//TRIM(label)//": ",value
      ELSE
         WRITE(*,'(A,ES14.6)') "PASS "//TRIM(label)//": ",value
      END IF
   END SUBROUTINE check_separation

   SUBROUTINE check_complex(label, value, expected, bound, failures)
      CHARACTER(LEN=*), INTENT(IN) :: label
      COMPLEX, INTENT(IN) :: value, expected
      REAL, INTENT(IN) :: bound
      INTEGER, INTENT(INOUT) :: failures

      CALL check_bound(label, ABS(value-expected), bound, failures)
   END SUBROUTINE check_complex

   SUBROUTINE check_real(label, value, expected, bound, failures)
      CHARACTER(LEN=*), INTENT(IN) :: label
      REAL, INTENT(IN) :: value, expected, bound
      INTEGER, INTENT(INOUT) :: failures

      CALL check_bound(label, ABS(value-expected), bound, failures)
   END SUBROUTINE check_real

   SUBROUTINE check_integer(label, value, expected, failures)
      CHARACTER(LEN=*), INTENT(IN) :: label
      INTEGER, INTENT(IN) :: value, expected
      INTEGER, INTENT(INOUT) :: failures

      IF (value /= expected) THEN
         failures = failures+1
         WRITE(*,'(A,2I8)') "FAIL "//TRIM(label)//": ", value, expected
      ELSE
         WRITE(*,'(A,I0)') "PASS "//TRIM(label)//": ", value
      END IF
   END SUBROUTINE check_integer

END PROGRAM spin_orbital_multipoles_test
