site_name: FLEUR
repo_url: https://iffgit.fz-juelich.de/fleur/fleur/
site_url: https://www.flapw.de/s/
repo_name: GIT
edit_url: edit/develop/docs/mkdocs/
nav:
    - Welcome: index.md
    - Further support: support.md
    - User Guide:
        - Overview: Docu-Main.md
        - Installation: Install.md
        - Running FLEUR: Running.md
        - The input-generator: inpgen.md
        - The FLEUR input file: xmlio.md
        - The FLEUR-AiiDA interface: http://aiida-fleur.readthedocs.io/en/develop/
    - Developers Infomation:
        - Fleur-GITLAB: https://iffgit.fz-juelich.de/fleur/fleur/
        - The DOXYGEN documentation of the source code: https://fleur.iffgit.fz-juelich.de/fleur/html
        - The coverage analysis: https://fleur.iffgit.fz-juelich.de/fleur/coverage_html
        - Developers Guide/Manual: developers.md
    - About/Impressum: about.md
