site_name: FLEUR
repo_url: https://iffgit.fz-juelich.de/fleur/fleur/
site_url: https://www.flapw.de/s/
repo_name: GIT
edit_uri: edit/develop/docs/mkdocs/docs/
nav:
    - Home:
        - Welcome: index.md
        - Downloads: downloads.md
        - Features and Description: features.md
        - Development Team: team.md
        - SPEX: spex.md
        - GFleur: gfleur.md
        - User support: support.md
        - Impressum: about.md
    - User Guide:
        - Overview: Docu-Main.md
        - Installation: Install.md
        - Running FLEUR: Running.md
        - The input-generator: inpgen.md
        - The FLEUR input file: xml-inp.md
        - More advanced settings: xml-advanced.md
        - The FLEUR-AiiDA interface: http://aiida-fleur.readthedocs.io/en/develop/
        - Glossary of typical expression: glossary.md
    - Tutorials/Examples: 
        - Tutorials: tutorials.md
        - Online tutorials: online-tutorials.md
        - Videos: video.md
        - Example inputs: examples.md
    - Developers Infomation:
        - Developers Home: develop-main.md
        - Fleur-GITLAB: https://iffgit.fz-juelich.de/fleur/fleur/
        - The DOXYGEN documentation of the source code: https://fleur.iffgit.fz-juelich.de/fleur/doxygen
        - The coverage analysis: https://fleur.iffgit.fz-juelich.de/fleur/coverage_html
        - Developers Guide/Manual: developers.md
plugins:
  - search
theme:
    name: cerulean
    custom_dir: tutorial_scheme
    extra_css: custom.css
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math
