perf-gfortran:
  image: iffregistry.fz-juelich.de/fleur/fleur:gfortran
  extends: .perf-generic
  tags:
    - iffcluster1703
  variables:
    BENCHER_TESTBED: GFortran-iffcluster
    OMP_NUM_THREADS: 16
  needs: 
    - build-gfortran-hdf5
  rules:
    - if: $CI_TASKS
      when: never
    - if: $CI_TASKS =~ /gfortran/  
    - when: on_success


perf-intel:
  image: iffregistry.fz-juelich.de/fleur/fleur:oneAPI
  extends: .perf-generic
  tags:
    - iffcluster1703
  variables:
    BUILD_FOLDER: "build.intel"
    BENCHER_TESTBED: IFORT-iffcluster
    OMP_NUM_THREADS: 16
  needs: 
    - build-intel
  rules:
      - if: $CI_TASKS =~ /intel/    

perf-intel-ifx:
  image: iffregistry.fz-juelich.de/fleur/fleur:oneAPI
  extends: .perf-generic
  tags:
    - iffcluster1703
  variables:
    BUILD_FOLDER: "build.intel.ifx"
    BENCHER_TESTBED: IFX-iffcluster
    OMP_NUM_THREADS: 16
  needs: 
    - build-intel-ifx
  rules:
      - if: $CI_TASKS =~ /intel/    


.perf-generic:
  variables:
    BENCHER_HOST: https://iffbencher.fz-juelich.de:16061
    BENCHER_PROJECT: fleur
    BENCHER_API_TOKEN: $BENCHER_TOKEN
    BENCHER_ADAPTER: json
    BENCHER_BRANCH: $CI_COMMIT_REF_NAME
  script:
    - cd $BUILD_FOLDER
    - ulimit -s unlimited ; sh ./run_tests.sh -perf
    - cp Testing/performance/*/bencher.json .
    - echo "$CI_COMMIT_REF_NAME"
    - bencher run --file bencher.json

