perf-gfortran:
  image: iffregistry.fz-juelich.de/fleur/fleur:gfortran
  extends: .perf-generic
  tags:
    - iffcluster1703
  variables:
    BENCHER_TESTBED: GFortran-iffcluster
    OMP_NUM_THREADS: 16
  before_script:
    - curl --proto '=https' --tlsv1.2 -sSfL https://bencher.dev/download/install-cli.sh | sh
  needs: 
    - build-gfortran-hdf5


perf-intel:
  image: iffregistry.fz-juelich.de/fleur/fleur:oneAPI
  extends: .perf-generic
  tags:
    - iffcluster1703
  variables:
    BUILD_FOLDER: "build.intel"
    BENCHER_TESTBED: IFORT-iffcluster
    OMP_NUM_THREADS: 16
  needs: 
    - build-intel
  rules:
      - if: $CI_TASKS =~ /intel/    

perf-intel-ifx:
  image: iffregistry.fz-juelich.de/fleur/fleur:oneAPI
  extends: .perf-generic
  tags:
    - iffcluster1703
  variables:
    BUILD_FOLDER: "build.intel.ifx"
    BENCHER_TESTBED: IFX-iffcluster
    OMP_NUM_THREADS: 16
  needs: 
    - build-intel-ifx
  rules:
      - if: $CI_TASKS =~ /intel/    


.perf-generic:
  variables:
    BENCHER_HOST: iffbencher.fz-juelich.de
    BENCHER_PROJECT: FLEUR
    BENCHER_API_TOKEN: $BENCHER_TOKEN
    BENCHER_ADAPTER: json
  script:
    - cd $BUILD_FOLDER
    - ulimit -s unlimited ; ./run_tests.sh -perf
    - cp Testing/performance/*/bencher.json .
    - bencher run --if-branch "$CI_COMMIT_REF_NAME" \\
        --else-if-branch "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" \\
        --file bencher.json

