build-gfortran-hdf5:
  image: iffregistry.fz-juelich.de/fleur/fleur:gfortran
  stage: build
  artifacts:
     paths:
       - build
     expire_in: 12h
  script:
    - cd $CI_PROJECT_DIR
    - ./configure.sh GITLAB
    - cd build
    - make -j 2
  rules:
    - if: $CI_TASKS
      when: never
    - if: $CI_TASKS =~ /gfortran/  
    - when: on_success


    

test-gfortran-hdf5: 
  image: iffregistry.fz-juelich.de/fleur/fleur:gfortran
  extends: .test-fleur
  variables:
    juDFT_MPI: "mpirun -n {mpi_procs} --allow-run-as-root --mca btl vader,self"
    markers: "not masci_tools"
  needs: 
    - fast-test-gfortran-hdf5
    - build-gfortran-hdf5
  rules:
    - if: $CI_TASKS
      when: never
    - if: $CI_TASKS =~ /gfortran/
    - when: on_success  

fast-test-gfortran-hdf5: 
  image: iffregistry.fz-juelich.de/fleur/fleur:gfortran
  extends: .test-fleur
  stage: fast-test
  variables:
    markers: "fast"
  needs: 
    - build-gfortran-hdf5
  rules:
    - if: $CI_TASKS
      when: never
    - if: $CI_TASKS =~ /gfortran/  
    - when: on_success

masci-test-gfortran-hdf5: 
  image: iffregistry.fz-juelich.de/fleur/fleur:gfortran
  extends: .test-fleur
  variables:
    juDFT_MPI: "mpirun -n {mpi_procs} --allow-run-as-root --mca btl vader,self"
    markers: "masci_tools"
  needs: 
    - build-gfortran-hdf5
  allow_failure: true
  rules:
    - if: $CI_TASKS
      when: never
    - if: $CI_TASKS =~ /gfortran/  
    - when: on_success


