build-gfortran-serial:
  image: iffregistry.fz-juelich.de/fleur/fleur:gfortran
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - ./configure.sh -l serial -mpi FALSE -hdf5 FALSE -cmake_opts -DFLEUR_USE_OPENMP=OFF
    - cd build.serial
    - make -j 2
  artifacts:
    paths:
      - build.serial
    expire_in: 12h
  rules:
    - if: $CI_TASKS =~ /serial/    
  
build-gfortran-hdf5-serial:
  image: iffregistry.fz-juelich.de/fleur/fleur:gfortran
  stage: build
  artifacts:
     paths:
       - build
     expire_in: 12h
  script:
    - cd $CI_PROJECT_DIR
    - ./configure.sh -m GITLAB -mpi FALSE
    - cd build
    - make -j 2
  rules:
      - if: $CI_TASKS =~ /serial/    

test-gfortran-serial:
  image: iffregistry.fz-juelich.de/fleur/fleur:gfortran
  extends: .test-fleur
  needs: 
    - build-gfortran-serial
  variables:
    BUILD_FOLDER: build.serial
    markers: "serial"
  rules:
    - if: $CI_TASKS =~ /serial/    
  
  
build-gfortran-hdf5-debug:
  image: iffregistry.fz-juelich.de/fleur/fleur:gfortran
  stage: build
  artifacts:
     paths:
       - build.debug
     expire_in: 12h
  script:
    - cd $CI_PROJECT_DIR
    - ./configure.sh -m GITLAB -mpi FALSE -d -flags "-fcheck=all -finit-real=snan -finit-derived"
    - cd build.debug
    - make -j 2
  rules:
      - if: $CI_TASKS =~ /debug/    

test-gfortran-serial-debug:
  image: iffregistry.fz-juelich.de/fleur/fleur:gfortran
  extends: .test-fleur
  needs: 
    - build-gfortran-hdf5-debug
  variables:
    BUILD_FOLDER: build.debug
    markers: "serial"
  rules:
    - if: $CI_TASKS =~ /debug/    
  
