build-gfortran-hdf5:
  image: iffregistry.fz-juelich.de/fleur/fleur:latest
  stage: build
  artifacts:
     paths:
       - build
     expire_in: 12h
  script:
    - cd $CI_PROJECT_DIR
    - ./configure.sh GITLAB
    - cd build
    - make -j 2



test-gfortran-hdf5: 
  image: iffregistry.fz-juelich.de/fleur/fleur:latest
  stage: test
  dependencies:
    - build-gfortran-hdf5
  needs: ["build-gfortran-hdf5"]
  script:
    - ulimit -s unlimited
    - export OMP_NUM_THREADS=2
    - export juDFT_MPI="mpirun -n {mpi_procs} --allow-run-as-root --mca btl vader,self"
    - cd $CI_PROJECT_DIR/build
    - mkdir -p Testing
    - export PYTEST_ADDOPTS="--test-summary-file=$CI_PROJECT_DIR/build/Testing/pytest_summary.out"
    - ./run_tests.sh | tee $CI_PROJECT_DIR/build/Testing/pytest_session.stdout
  artifacts:
    when: always
    paths:
      - build/Testing



