image:
  name: iffregistry.fz-juelich.de/fleur/fleur:NVHPC
  entrypoint: ["/usr/bin/bash -i -c"]

build-pgi:
  image: iffregistry.fz-juelich.de/fleur/fleur:NVHPC
  stage: build
  artifacts:
     paths:
       - build.pgi
     expire_in: 12h
  script:
    - /bin/bash -i -c "cd $CI_PROJECT_DIR; ./configure.sh -l pgi -c auto; cd build.pgi; make"
  allow_failure: true
  rules:
      - if: $CI_TASKS =~ /nvidia/    
  
test-pgi:
  image: iffregistry.fz-juelich.de/fleur/fleur:NVHPC
  extends: .test-fleur
  variables:
    BUILD_FOLDER: build.pgi
  needs: 
    - build-pgi
  allow_failure: true
  rules:
      - if: $CI_TASKS =~ /nvidia/    
  
build-nvhpc-gpu:
  image:  
  stage: build
  tags:
      - rtx2080ti
  artifacts:
    paths:
      - build.nvgpu
    expire_in: 12h
  script:
    - cd $CI_PROJECT_DIR; LDFLAGS="-Wl,--copy-dt-needed-entries -llapack" FC=/opt/nvidia_hpc_sdk/Linux_x86_64/2023/compilers/bin/nvfortran ./configure.sh  -l nvgpu -c auto -gpu acc:cc60 -make
  allow_failure: true
  rules:
    - if: $CI_TASKS =~ /gpu/


test-nvhpc-gpu:
  image: 
  extends: .test-fleur
  tags:
     - rtx2080ti
  variables:
    BUILD_FOLDER: build.nvgpu
    LD_LIBRARY_PATH: /opt/nvidia_hpc_sdk/Linux_x86_64/23.9/cuda/12.2/targets/x86_64-linux/lib:${LD_LIBRARY_PATH}
  before_script:
    - pip install pytest-html  
  needs: 
    - build-nvhpc-gpu
  allow_failure: true
  rules:
      - if: $CI_TASKS =~ /gpu/    
  