build-intel:
  image: iffregistry.fz-juelich.de/fleur/fleur:oneAPI
  stage: build
  artifacts:
     paths:
       - build.intel
     expire_in: 12h
  script:
    - cd $CI_PROJECT_DIR
    - ./configure.sh -l intel
    - cd build.intel
    - make -j 2
  allow_failure: false
  rules:
    - if: $CI_PIPELINE_SOURCE != "push"   

test-intel:
  image: iffregistry.fz-juelich.de/fleur/fleur:oneAPI
  extends: .test-fleur-not-on-push
  variables:
    BUILD_FOLDER: "build.intel"
    juDFT_MPI: "mpirun -n {mpi_procs} "
  needs: 
    - build-intel
  allow_failure: true
