build-intel:
  image: iffregistry.fz-juelich.de/fleur/fleur:oneAPI
  stage: build
  artifacts:
     paths:
       - build.intel
     expire_in: 12h
  script:
    - cd $CI_PROJECT_DIR
    - ./configure.sh -l intel
    - cd build.intel
    - make -j 2
  allow_failure: false
  rules:
      - if: $CI_TASKS =~ /intel/

test-intel:
  image: iffregistry.fz-juelich.de/fleur/fleur:oneAPI
  extends: .test-fleur
  variables:
    BUILD_FOLDER: "build.intel"
  needs: 
    - build-intel
  allow_failure: true
  rules:
      - if: $CI_TASKS =~ /intel/    

build-intel-ifx:
  image: iffregistry.fz-juelich.de/fleur/fleur:oneAPI
  stage: build
  artifacts:
     paths:
       - build.intel.ifx
     expire_in: 12h
  script:
    - cd $CI_PROJECT_DIR
    - FC=ifx ./configure.sh -l intel.ifx
    - cd build.intel.ifx
    - make -j 2
  allow_failure: false
  rules:
      - if: $CI_TASKS =~ /intel/

test-intel-ifx:
  image: iffregistry.fz-juelich.de/fleur/fleur:oneAPI
  extends: .test-fleur
  variables:
    BUILD_FOLDER: "build.intel.ifx"
  needs: 
    - build-intel-ifx
  allow_failure: true
  rules:
      - if: $CI_TASKS =~ /intel/    
  
build-intel-debug:
  image: iffregistry.fz-juelich.de/fleur/fleur:oneAPI
  stage: build
  artifacts:
     paths:
       - build.intel.debug
     expire_in: 12h
  script:
    - cd $CI_PROJECT_DIR
    - ./configure.sh -l intel -d -flags "-init=array,snan,huge -ftrapuv "
    - cd build.intel.debug
    - make -j 2
  allow_failure: false
  rules:
      - if: $CI_TASKS =~ /debug/

test-intel-debug:
  image: iffregistry.fz-juelich.de/fleur/fleur:oneAPI
  extends: .test-fleur
  variables:
    BUILD_FOLDER: "build.intel.debug"
  needs: 
    - build-intel-debug
  allow_failure: true
  rules:
      - if: $CI_TASKS =~ /debug/    
  
