build-intel:
  image: iffregistry.fz-juelich.de/fleur/fleur:oneAPI
  stage: build
  artifacts:
     paths:
       - build.intel
     expire_in: 12h
  script:
    - cd $CI_PROJECT_DIR
    - ./configure.sh -l intel
    - cd build.intel
    - make -j 2
  allow_failure: false
  rules:
      - if: $CI_TASKS =~ /intel/

test-intel:
  image: iffregistry.fz-juelich.de/fleur/fleur:oneAPI
  extends: .test-fleur
  variables:
    BUILD_FOLDER: "build.intel"
  needs: 
    - build-intel
  allow_failure: true
  rules:
      - if: $CI_TASKS =~ /intel/    
  
