# Profile-driven compiler flag selection and capability probing.

include(CheckCCompilerFlag)
include(CheckFortranCompilerFlag)

set(FLEUR_CPU_PROFILE "native" CACHE STRING "CPU optimization profile")
set_property(CACHE FLEUR_CPU_PROFILE PROPERTY STRINGS portable native x86_64_v2 x86_64_v3 x86_64_v4 avx2 zen2 zen3 zen4 armv8 a64fx)

set(FLEUR_OPT_LEVEL "performance" CACHE STRING "Optimization policy")
set_property(CACHE FLEUR_OPT_LEVEL PROPERTY STRINGS safe performance debug)

set(FLEUR_ELPA_KERNEL_PROFILE "auto" CACHE STRING "ELPA kernel profile")
set_property(CACHE FLEUR_ELPA_KERNEL_PROFILE PROPERTY STRINGS auto generic x86 avx2 avx512 arm gpu)

set(FLEUR_STRICT_ARCH_FLAGS ON CACHE BOOL "Fail configure if requested architecture flags are not available")

if (DEFINED CLI_FLEUR_CPU_PROFILE AND NOT CLI_FLEUR_CPU_PROFILE STREQUAL "")
  set(FLEUR_CPU_PROFILE "${CLI_FLEUR_CPU_PROFILE}" CACHE STRING "CPU optimization profile" FORCE)
endif()
if (DEFINED CLI_FLEUR_OPT_LEVEL AND NOT CLI_FLEUR_OPT_LEVEL STREQUAL "")
  set(FLEUR_OPT_LEVEL "${CLI_FLEUR_OPT_LEVEL}" CACHE STRING "Optimization policy" FORCE)
endif()
if (DEFINED CLI_FLEUR_ELPA_KERNEL_PROFILE AND NOT CLI_FLEUR_ELPA_KERNEL_PROFILE STREQUAL "")
  set(FLEUR_ELPA_KERNEL_PROFILE "${CLI_FLEUR_ELPA_KERNEL_PROFILE}" CACHE STRING "ELPA kernel profile" FORCE)
endif()

set(_fleur_valid_cpu_profiles portable native x86_64_v2 x86_64_v3 x86_64_v4 avx2 zen2 zen3 zen4 armv8 a64fx)
list(FIND _fleur_valid_cpu_profiles "${FLEUR_CPU_PROFILE}" _fleur_cpu_profile_idx)
if (_fleur_cpu_profile_idx EQUAL -1)
  message(FATAL_ERROR "Invalid FLEUR_CPU_PROFILE='${FLEUR_CPU_PROFILE}'.")
endif()

set(_fleur_valid_opt_levels safe performance debug)
list(FIND _fleur_valid_opt_levels "${FLEUR_OPT_LEVEL}" _fleur_opt_level_idx)
if (_fleur_opt_level_idx EQUAL -1)
  message(FATAL_ERROR "Invalid FLEUR_OPT_LEVEL='${FLEUR_OPT_LEVEL}'.")
endif()

set(_fleur_valid_elpa_profiles auto generic x86 avx2 avx512 arm gpu)
list(FIND _fleur_valid_elpa_profiles "${FLEUR_ELPA_KERNEL_PROFILE}" _fleur_elpa_profile_idx)
if (_fleur_elpa_profile_idx EQUAL -1)
  message(FATAL_ERROR "Invalid FLEUR_ELPA_KERNEL_PROFILE='${FLEUR_ELPA_KERNEL_PROFILE}'.")
endif()

string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" _fleur_proc)
if (_fleur_proc MATCHES "^(x86_64|amd64)$")
  set(FLEUR_ARCH_FAMILY "x86_64")
elseif (_fleur_proc MATCHES "^(aarch64|arm64)$")
  set(FLEUR_ARCH_FAMILY "aarch64")
else()
  set(FLEUR_ARCH_FAMILY "other")
endif()

set(FLEUR_CPU_VENDOR "unknown")
if (_fleur_proc MATCHES "znver|amd")
  set(FLEUR_CPU_VENDOR "amd")
elseif (_fleur_proc MATCHES "intel")
  set(FLEUR_CPU_VENDOR "intel")
elseif (_fleur_proc MATCHES "arm|aarch64")
  set(FLEUR_CPU_VENDOR "arm")
endif()

if (NOT FLEUR_CPU_PROFILE)
  set(FLEUR_CPU_PROFILE "native" CACHE STRING "CPU optimization profile" FORCE)
endif()

set(FLEUR_HOST_X86_AVX2 OFF)
set(FLEUR_HOST_X86_AVX512 OFF)
if (FLEUR_ARCH_FAMILY STREQUAL "x86_64")
  set(_fleur_cpu_feature_text "")
  if (APPLE)
    execute_process(COMMAND sysctl -n machdep.cpu.features
      OUTPUT_VARIABLE _fleur_cpu_feat_a
      ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    execute_process(COMMAND sysctl -n machdep.cpu.leaf7_features
      OUTPUT_VARIABLE _fleur_cpu_feat_b
      ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    set(_fleur_cpu_feature_text "${_fleur_cpu_feat_a} ${_fleur_cpu_feat_b}")
  elseif (EXISTS "/proc/cpuinfo")
    file(READ "/proc/cpuinfo" _fleur_cpu_feature_text)
  endif()

  string(TOLOWER "${_fleur_cpu_feature_text}" _fleur_cpu_feature_text)
  if (_fleur_cpu_feature_text MATCHES "(^|[ ,\n\t])avx2([ ,\n\t]|$)")
    set(FLEUR_HOST_X86_AVX2 ON)
  endif()
  if (_fleur_cpu_feature_text MATCHES "(^|[ ,\n\t])avx512f([ ,\n\t]|$)")
    set(FLEUR_HOST_X86_AVX512 ON)
  endif()
endif()

function(_fleur_profile_issue msg)
  if (FLEUR_STRICT_ARCH_FLAGS)
    message(FATAL_ERROR "${msg}")
  else()
    message(WARNING "${msg}")
  endif()
endfunction()

set(_fleur_x86_profiles x86_64_v2 x86_64_v3 x86_64_v4 avx2 zen2 zen3 zen4)
set(_fleur_arm_profiles armv8 a64fx)

list(FIND _fleur_x86_profiles "${FLEUR_CPU_PROFILE}" _fleur_x86_profile_idx)
if (NOT FLEUR_ARCH_FAMILY STREQUAL "x86_64" AND NOT _fleur_x86_profile_idx EQUAL -1)
  _fleur_profile_issue("FLEUR_CPU_PROFILE='${FLEUR_CPU_PROFILE}' requires x86_64, but detected CMAKE_SYSTEM_PROCESSOR='${CMAKE_SYSTEM_PROCESSOR}'.")
endif()

list(FIND _fleur_arm_profiles "${FLEUR_CPU_PROFILE}" _fleur_arm_profile_idx)
if (NOT FLEUR_ARCH_FAMILY STREQUAL "aarch64" AND NOT _fleur_arm_profile_idx EQUAL -1)
  _fleur_profile_issue("FLEUR_CPU_PROFILE='${FLEUR_CPU_PROFILE}' requires aarch64/arm64, but detected CMAKE_SYSTEM_PROCESSOR='${CMAKE_SYSTEM_PROCESSOR}'.")
endif()

if (NOT FLEUR_ELPA_KERNEL_PROFILE STREQUAL "auto")
  if (FLEUR_ELPA_KERNEL_PROFILE MATCHES "^(x86|avx2|avx512)$" AND NOT FLEUR_ARCH_FAMILY STREQUAL "x86_64")
    _fleur_profile_issue("FLEUR_ELPA_KERNEL_PROFILE='${FLEUR_ELPA_KERNEL_PROFILE}' requires x86_64, but detected CMAKE_SYSTEM_PROCESSOR='${CMAKE_SYSTEM_PROCESSOR}'.")
  endif()
  if (FLEUR_ELPA_KERNEL_PROFILE STREQUAL "arm" AND NOT FLEUR_ARCH_FAMILY STREQUAL "aarch64")
    _fleur_profile_issue("FLEUR_ELPA_KERNEL_PROFILE='arm' requires aarch64/arm64, but detected CMAKE_SYSTEM_PROCESSOR='${CMAKE_SYSTEM_PROCESSOR}'.")
  endif()
endif()

set(_fleur_compiler_supported_profiles portable native)
if (CMAKE_Fortran_COMPILER_ID MATCHES "Intel")
  list(APPEND _fleur_compiler_supported_profiles x86_64_v2 x86_64_v3 x86_64_v4 avx2 zen2 zen3 zen4)
elseif (CMAKE_Fortran_COMPILER_ID MATCHES "NVHPC|PGI")
  list(APPEND _fleur_compiler_supported_profiles x86_64_v3 x86_64_v4 avx2 zen2 zen3 armv8)
elseif (CMAKE_Fortran_COMPILER_ID MATCHES "GNU")
  list(APPEND _fleur_compiler_supported_profiles x86_64_v2 x86_64_v3 x86_64_v4 avx2 zen2 zen3 zen4 armv8 a64fx)
else()
  _fleur_profile_issue("No explicit CPU profile mapping is implemented for compiler '${CMAKE_Fortran_COMPILER_ID}'. Only generic behavior may be used.")
endif()

list(FIND _fleur_compiler_supported_profiles "${FLEUR_CPU_PROFILE}" _fleur_profile_supported_idx)
if (_fleur_profile_supported_idx EQUAL -1)
  string(REPLACE ";" ", " _fleur_supported_profiles_str "${_fleur_compiler_supported_profiles}")
  _fleur_profile_issue("FLEUR_CPU_PROFILE='${FLEUR_CPU_PROFILE}' is not mapped for compiler '${CMAKE_Fortran_COMPILER_ID}'. Supported profiles: ${_fleur_supported_profiles_str}.")
endif()

function(_fleur_flag_var_name lang flag outvar)
  string(REGEX REPLACE "^-+" "" _tmp "${flag}")
  string(REGEX REPLACE "[^A-Za-z0-9]" "_" _tmp "${_tmp}")
  string(TOUPPER "${_tmp}" _tmp)
  if (lang STREQUAL "Fortran")
    set(${outvar} "FLEUR_HAVE_FC_FLAG_${_tmp}" PARENT_SCOPE)
  else()
    set(${outvar} "FLEUR_HAVE_CC_FLAG_${_tmp}" PARENT_SCOPE)
  endif()
endfunction()

function(_fleur_test_and_collect lang flag selected_var available_var)
  _fleur_flag_var_name("${lang}" "${flag}" _cache_var)

  if (NOT DEFINED ${_cache_var})
    if (lang STREQUAL "Fortran")
      check_fortran_compiler_flag("${flag}" ${_cache_var})
    else()
      check_c_compiler_flag("${flag}" ${_cache_var})
    endif()
    set(${_cache_var} "${${_cache_var}}" CACHE BOOL "Compiler support for ${lang} flag ${flag}" FORCE)
  endif()

  if (${_cache_var})
    set(_selected "${${selected_var}}")
    if (_selected)
      set(_selected "${_selected} ${flag}")
    else()
      set(_selected "${flag}")
    endif()
    set(${selected_var} "${_selected}" PARENT_SCOPE)
  endif()

  set(_available "${${available_var}}")
  if (_available)
    set(_available "${_available};${flag}=${${_cache_var}}")
  else()
    set(_available "${flag}=${${_cache_var}}")
  endif()
  set(${available_var} "${_available}" PARENT_SCOPE)
endfunction()

set(_fleur_fc_arch_candidates "")
set(_fleur_cc_arch_candidates "")

if (CMAKE_Fortran_COMPILER_ID MATCHES "Intel")
  if (FLEUR_CPU_PROFILE STREQUAL "native")
    list(APPEND _fleur_fc_arch_candidates "-xHost")
    list(APPEND _fleur_cc_arch_candidates "-xHost")
  elseif (FLEUR_CPU_PROFILE STREQUAL "x86_64_v4")
    list(APPEND _fleur_fc_arch_candidates "-xCORE-AVX512")
    list(APPEND _fleur_cc_arch_candidates "-xCORE-AVX512")
  elseif (FLEUR_CPU_PROFILE MATCHES "x86_64_v3|zen2|zen3|zen4")
    list(APPEND _fleur_fc_arch_candidates "-mavx2")
    list(APPEND _fleur_cc_arch_candidates "-mavx2")
  elseif (FLEUR_CPU_PROFILE STREQUAL "x86_64_v2")
    list(APPEND _fleur_fc_arch_candidates "-msse4.2")
    list(APPEND _fleur_cc_arch_candidates "-msse4.2")
  elseif (FLEUR_CPU_PROFILE STREQUAL "portable")
    list(APPEND _fleur_fc_arch_candidates "-axCORE-AVX2")
    list(APPEND _fleur_cc_arch_candidates "-axCORE-AVX2")
  endif()
elseif (CMAKE_Fortran_COMPILER_ID MATCHES "NVHPC|PGI")
  if (FLEUR_CPU_PROFILE STREQUAL "native")
    list(APPEND _fleur_fc_arch_candidates "-tp=host")
    list(APPEND _fleur_cc_arch_candidates "-tp=host")
  elseif (FLEUR_CPU_PROFILE STREQUAL "x86_64_v3" OR FLEUR_CPU_PROFILE STREQUAL "x86_64_v4" OR FLEUR_CPU_PROFILE STREQUAL "avx2")
    list(APPEND _fleur_fc_arch_candidates "-tp=haswell")
    list(APPEND _fleur_cc_arch_candidates "-tp=haswell")
  elseif (FLEUR_CPU_PROFILE STREQUAL "zen2")
    list(APPEND _fleur_fc_arch_candidates "-tp=zen2")
    list(APPEND _fleur_cc_arch_candidates "-tp=zen2")
  elseif (FLEUR_CPU_PROFILE STREQUAL "zen3")
    list(APPEND _fleur_fc_arch_candidates "-tp=zen3")
    list(APPEND _fleur_cc_arch_candidates "-tp=zen3")
  elseif (FLEUR_CPU_PROFILE STREQUAL "armv8")
    list(APPEND _fleur_fc_arch_candidates "-tp=neoverse-v1")
    list(APPEND _fleur_cc_arch_candidates "-tp=neoverse-v1")
  endif()
elseif (CMAKE_Fortran_COMPILER_ID MATCHES "GNU")
  if (FLEUR_CPU_PROFILE STREQUAL "native")
    list(APPEND _fleur_fc_arch_candidates "-march=native")
    list(APPEND _fleur_cc_arch_candidates "-march=native")
  elseif (FLEUR_CPU_PROFILE STREQUAL "x86_64_v4")
    list(APPEND _fleur_fc_arch_candidates "-march=x86-64-v4")
    list(APPEND _fleur_cc_arch_candidates "-march=x86-64-v4")
  elseif (FLEUR_CPU_PROFILE STREQUAL "x86_64_v3")
    list(APPEND _fleur_fc_arch_candidates "-march=x86-64-v3")
    list(APPEND _fleur_cc_arch_candidates "-march=x86-64-v3")
  elseif (FLEUR_CPU_PROFILE STREQUAL "x86_64_v2")
    list(APPEND _fleur_fc_arch_candidates "-march=x86-64-v2")
    list(APPEND _fleur_cc_arch_candidates "-march=x86-64-v2")
  elseif (FLEUR_CPU_PROFILE STREQUAL "zen2")
    list(APPEND _fleur_fc_arch_candidates "-march=znver2")
    list(APPEND _fleur_cc_arch_candidates "-march=znver2")
  elseif (FLEUR_CPU_PROFILE STREQUAL "zen3")
    list(APPEND _fleur_fc_arch_candidates "-march=znver3")
    list(APPEND _fleur_cc_arch_candidates "-march=znver3")
  elseif (FLEUR_CPU_PROFILE STREQUAL "zen4")
    list(APPEND _fleur_fc_arch_candidates "-march=znver4")
    list(APPEND _fleur_cc_arch_candidates "-march=znver4")
  elseif (FLEUR_CPU_PROFILE STREQUAL "armv8")
    list(APPEND _fleur_fc_arch_candidates "-march=armv8-a")
    list(APPEND _fleur_cc_arch_candidates "-march=armv8-a")
  elseif (FLEUR_CPU_PROFILE STREQUAL "a64fx")
    list(APPEND _fleur_fc_arch_candidates "-mcpu=a64fx")
    list(APPEND _fleur_cc_arch_candidates "-mcpu=a64fx")
  endif()
endif()

if (FLEUR_OPT_LEVEL STREQUAL "safe")
  if (CMAKE_Fortran_COMPILER_ID MATCHES "GNU")
    set(_fleur_fc_arch_candidates "")
    set(_fleur_cc_arch_candidates "")
  endif()
endif()

set(_fleur_fc_selected "")
set(_fleur_fc_available "")
foreach(_flag IN LISTS _fleur_fc_arch_candidates)
  _fleur_test_and_collect("Fortran" "${_flag}" _fleur_fc_selected _fleur_fc_available)
endforeach()

set(_fleur_cc_selected "")
set(_fleur_cc_available "")
foreach(_flag IN LISTS _fleur_cc_arch_candidates)
  _fleur_test_and_collect("C" "${_flag}" _fleur_cc_selected _fleur_cc_available)
endforeach()

set(FLEUR_FORTRAN_ARCH_FLAGS_SELECTED "${_fleur_fc_selected}" CACHE STRING "Selected Fortran architecture flags" FORCE)
set(FLEUR_C_ARCH_FLAGS_SELECTED "${_fleur_cc_selected}" CACHE STRING "Selected C architecture flags" FORCE)
set(FLEUR_FORTRAN_ARCH_FLAGS_AVAILABLE "${_fleur_fc_available}" CACHE STRING "Fortran architecture flag availability" FORCE)
set(FLEUR_C_ARCH_FLAGS_AVAILABLE "${_fleur_cc_available}" CACHE STRING "C architecture flag availability" FORCE)

if (NOT FLEUR_CPU_PROFILE MATCHES "^(portable|native)$" AND NOT FLEUR_FORTRAN_ARCH_FLAGS_SELECTED)
  _fleur_profile_issue("No architecture flags selected for FLEUR_CPU_PROFILE='${FLEUR_CPU_PROFILE}' with compiler '${CMAKE_Fortran_COMPILER_ID}'. Falling back to generic flags.")
endif()

if (FLEUR_STRICT_ARCH_FLAGS)
  if (_fleur_fc_arch_candidates AND NOT FLEUR_FORTRAN_ARCH_FLAGS_SELECTED)
    message(FATAL_ERROR "Requested CPU profile '${FLEUR_CPU_PROFILE}' produced no supported Fortran architecture flags.")
  endif()
endif()

if (FLEUR_ELPA_KERNEL_PROFILE STREQUAL "auto")
  if (FLEUR_USE_GPU)
    set(FLEUR_ELPA_KERNEL_MODE "gpu")
  elseif (FLEUR_ARCH_FAMILY STREQUAL "aarch64")
    set(FLEUR_ELPA_KERNEL_MODE "arm")
  elseif (FLEUR_CPU_PROFILE STREQUAL "x86_64_v4")
    set(FLEUR_ELPA_KERNEL_MODE "avx512")
  elseif (FLEUR_CPU_PROFILE MATCHES "x86_64_v3|zen2|zen3|zen4")
    set(FLEUR_ELPA_KERNEL_MODE "avx2")
  elseif (FLEUR_ARCH_FAMILY STREQUAL "x86_64")
    set(FLEUR_ELPA_KERNEL_MODE "x86")
  else()
    set(FLEUR_ELPA_KERNEL_MODE "generic")
  endif()
else()
  set(FLEUR_ELPA_KERNEL_MODE "${FLEUR_ELPA_KERNEL_PROFILE}")
endif()

set(_fleur_elpa_kernel_downgrade 0)
if (FLEUR_ELPA_KERNEL_MODE STREQUAL "avx2")
  if ((NOT FLEUR_FORTRAN_ARCH_FLAGS_SELECTED MATCHES "avx2|x86-64-v3|znver2|znver3|znver4|haswell") OR
      (NOT FLEUR_C_ARCH_FLAGS_SELECTED MATCHES "avx2|x86-64-v3|znver2|znver3|znver4|haswell"))
    _fleur_profile_issue("ELPA kernel mode 'avx2' requested but selected Fortran/C architecture flags do not both indicate AVX2 support. Falling back to generic ELPA kernels.")
    set(_fleur_elpa_kernel_downgrade 1)
  endif()
  if (FLEUR_ARCH_FAMILY STREQUAL "x86_64" AND NOT FLEUR_HOST_X86_AVX2)
    _fleur_profile_issue("ELPA kernel mode 'avx2' requested but host CPU does not report AVX2 support. Falling back to generic ELPA kernels.")
    set(_fleur_elpa_kernel_downgrade 1)
  endif()
elseif (FLEUR_ELPA_KERNEL_MODE STREQUAL "avx512")
  if ((NOT FLEUR_FORTRAN_ARCH_FLAGS_SELECTED MATCHES "avx512|x86-64-v4") OR
      (NOT FLEUR_C_ARCH_FLAGS_SELECTED MATCHES "avx512|x86-64-v4"))
    _fleur_profile_issue("ELPA kernel mode 'avx512' requested but selected Fortran/C architecture flags do not both indicate AVX512 support. Falling back to generic ELPA kernels.")
    set(_fleur_elpa_kernel_downgrade 1)
  endif()
  if (FLEUR_ARCH_FAMILY STREQUAL "x86_64" AND NOT FLEUR_HOST_X86_AVX512)
    _fleur_profile_issue("ELPA kernel mode 'avx512' requested but host CPU does not report AVX512F support. Falling back to generic ELPA kernels.")
    set(_fleur_elpa_kernel_downgrade 1)
  endif()
elseif (FLEUR_ELPA_KERNEL_MODE STREQUAL "arm")
  if (NOT FLEUR_ARCH_FAMILY STREQUAL "aarch64")
    _fleur_profile_issue("ELPA kernel mode 'arm' requested but detected architecture family is '${FLEUR_ARCH_FAMILY}'. Falling back to generic ELPA kernels.")
    set(_fleur_elpa_kernel_downgrade 1)
  endif()
elseif (FLEUR_ELPA_KERNEL_MODE STREQUAL "x86")
  if (NOT FLEUR_ARCH_FAMILY STREQUAL "x86_64")
    _fleur_profile_issue("ELPA kernel mode 'x86' requested but detected architecture family is '${FLEUR_ARCH_FAMILY}'. Falling back to generic ELPA kernels.")
    set(_fleur_elpa_kernel_downgrade 1)
  endif()
endif()

if (_fleur_elpa_kernel_downgrade)
  set(FLEUR_ELPA_KERNEL_MODE "generic")
endif()

set(FLEUR_ELPA_KERNEL_FLAGS_SELECTED "--enable-generic-kernels")
if (NOT FLEUR_ELPA_KERNEL_MODE STREQUAL "avx512")
  set(FLEUR_ELPA_KERNEL_FLAGS_SELECTED "${FLEUR_ELPA_KERNEL_FLAGS_SELECTED} --disable-avx512-kernels")
endif()
if (FLEUR_ELPA_KERNEL_MODE STREQUAL "x86")
  set(FLEUR_ELPA_KERNEL_FLAGS_SELECTED "${FLEUR_ELPA_KERNEL_FLAGS_SELECTED} --enable-sse-kernels --enable-avx-kernels")
elseif (FLEUR_ELPA_KERNEL_MODE STREQUAL "avx2")
  set(FLEUR_ELPA_KERNEL_FLAGS_SELECTED "${FLEUR_ELPA_KERNEL_FLAGS_SELECTED} --enable-sse-kernels --enable-avx-kernels --enable-avx2-kernels")
elseif (FLEUR_ELPA_KERNEL_MODE STREQUAL "avx512")
  set(FLEUR_ELPA_KERNEL_FLAGS_SELECTED "${FLEUR_ELPA_KERNEL_FLAGS_SELECTED} --enable-sse-kernels --enable-avx-kernels --enable-avx2-kernels --enable-avx512-kernels")
elseif (FLEUR_ELPA_KERNEL_MODE STREQUAL "arm")
  set(FLEUR_ELPA_KERNEL_FLAGS_SELECTED "${FLEUR_ELPA_KERNEL_FLAGS_SELECTED}")
elseif (FLEUR_ELPA_KERNEL_MODE STREQUAL "gpu")
  set(FLEUR_ELPA_KERNEL_FLAGS_SELECTED "${FLEUR_ELPA_KERNEL_FLAGS_SELECTED}")
endif()
set(FLEUR_ELPA_KERNEL_FLAGS_SELECTED "${FLEUR_ELPA_KERNEL_FLAGS_SELECTED}" CACHE STRING "ELPA kernel configure flags selected by FLEUR" FORCE)

message(STATUS "FLEUR CPU profile: ${FLEUR_CPU_PROFILE} (arch=${FLEUR_ARCH_FAMILY}, vendor=${FLEUR_CPU_VENDOR})")
if (FLEUR_ARCH_FAMILY STREQUAL "x86_64")
  message(STATUS "FLEUR host CPU features: AVX2=${FLEUR_HOST_X86_AVX2}, AVX512F=${FLEUR_HOST_X86_AVX512}")
endif()
message(STATUS "FLEUR selected Fortran arch flags: ${FLEUR_FORTRAN_ARCH_FLAGS_SELECTED}")
message(STATUS "FLEUR selected C arch flags: ${FLEUR_C_ARCH_FLAGS_SELECTED}")
message(STATUS "FLEUR ELPA kernel mode: ${FLEUR_ELPA_KERNEL_MODE}")
