#Targets for the Green's-function embedding code (gfleur).
#
#The gfleur executables are built from the full FLEUR source list plus the
#sources in src/gfleur-embedding, replacing only the main program. All
#persistent I/O of gfleur is HDF5-based, so the targets are skipped entirely
#if HDF5 is not available.

if (FLEUR_USE_HDF5)
   include(src/gfleur-embedding/CMakeLists.txt)
   set(gfleur_SRC ${fleur_SRC} ${gfleur_F90})
   list(REMOVE_ITEM gfleur_SRC src/fleur/main/fleur_prog.F90)
   set_source_files_properties(${gfleur_F90} PROPERTIES Fortran_FORMAT FREE)

   if (FLEUR_USE_SERIAL)
      add_executable(gfleur ${gfleur_SRC} ${c_filesFleur})
      target_compile_definitions(gfleur PUBLIC ${FLEUR_DEFINITIONS})
      target_compile_options(gfleur PUBLIC $<$<COMPILE_LANGUAGE:Fortran>:${FLEUR_PRECISION_OPTION}>)
      target_link_libraries(gfleur fleurinput juDFT)
      if (FLEUR_COMPILE_EDSOLVER)
         target_link_libraries(gfleur EDsolver)
      endif()
      if (FLEUR_COMPILE_MAGMA)
         target_link_libraries(gfleur magma)
      endif()
      target_link_libraries(gfleur ${FLEUR_LIBRARIES})
      target_link_libraries(gfleur ${FLEUR_LINK_LIBRARIES})
      target_compile_options(gfleur PRIVATE $<$<COMPILE_LANGUAGE:Fortran>:${FLEUR_COMPILE_OPTIONS}>)
      target_compile_options(gfleur PRIVATE -Imodules/gfleur)
      set_target_properties(gfleur PROPERTIES Fortran_MODULE_DIRECTORY modules/gfleur)
   endif()

   if (FLEUR_USE_MPI)
      add_executable(gfleur_MPI ${gfleur_SRC} ${c_filesFleur})
      target_compile_definitions(gfleur_MPI PUBLIC ${FLEUR_MPI_DEFINITIONS})
      target_link_libraries(gfleur_MPI fleurinput juDFT)
      target_compile_options(gfleur_MPI PUBLIC $<$<COMPILE_LANGUAGE:Fortran>:${FLEUR_PRECISION_OPTION}>)
      target_compile_options(gfleur_MPI PUBLIC $<$<COMPILE_LANGUAGE:Fortran>:${FLEUR_COMPILE_OPTIONS}>)
      if (FLEUR_COMPILE_EDSOLVER)
         target_link_libraries(gfleur_MPI EDsolver)
      endif()
      if (FLEUR_COMPILE_MAGMA)
         target_link_libraries(gfleur_MPI magma)
      endif()
      if (FLEUR_COMPILE_CHASE)
         target_link_libraries(gfleur_MPI chase_f)
         set_target_properties(gfleur_MPI PROPERTIES LINKER_LANGUAGE Fortran)
      endif()
      if (FLEUR_COMPILE_ELSI)
         add_dependencies(gfleur_MPI elsi)
         target_link_libraries(gfleur_MPI elsi)
         set_target_properties(gfleur_MPI PROPERTIES LINKER_LANGUAGE Fortran)
      endif()
      if (FLEUR_USE_INTERNAL_ELPA)
         if (TARGET ELPA)
            add_dependencies(gfleur_MPI ELPA)
         endif()
         add_dependencies(gfleur_MPI elpa)
         target_link_libraries(gfleur_MPI elpa)
         target_link_libraries(gfleur_MPI "-lstdc++")
      endif()
      if (FLEUR_COMPILE_SCALAPACK)
         target_link_libraries(gfleur_MPI scalapack)
      endif()
      target_link_libraries(gfleur_MPI ${FLEUR_LIBRARIES})
      target_link_libraries(gfleur_MPI ${FLEUR_LINK_LIBRARIES})
      set_target_properties(gfleur_MPI PROPERTIES Fortran_MODULE_DIRECTORY modules/gfleur_MPI)
      target_compile_options(gfleur_MPI PUBLIC -Imodules/gfleur_MPI)
   endif()
else()
   message(STATUS "gfleur targets skipped: HDF5 is required")
endif()
